In [4]:
# CODE FÜR BERT
!pip install -q transformers sentencepiece

from transformers import pipeline
import pandas as pd

# 1) Load English BERT for masked-word prediction
fill_mask = pipeline("fill-mask", model="bert-base-uncased")

# 2) Children-story style cloze sentences (English)
#    Format: (masked_text, expected_word)
kids_en = [
    ("Little Red Riding Hood walked into the forest and met the [MASK].", "wolf"),
    ("The king sat on his [MASK] and spoke to the people.", "throne"),
    ("The wizard raised his [MASK] and whispered a spell.", "staff"),
    ("The little boy lost his [MASK] in the snow.", "hat"),
    ("The brave knight drew his [MASK] to fight the dragon.", "sword"),
    ("The witch offered a poisoned [MASK] to the girl.", "apple"),
    ("The princess opened the old [MASK] and looked inside.", "door"),
    ("The giant lived at the top of the tall [MASK].", "tower"),
    ("The fairy waved her [MASK] and the room sparkled.", "wand"),
    ("The rabbit ran so fast that the [MASK] could not catch up.", "turtle"),
]

# 3) Run evaluation
rows = []
for text, gold in kids_en:
    preds = fill_mask(text)  # list of dicts
    top5 = [p["token_str"].strip() for p in preds[:5]]
    top1 = top5[0]

    rows.append({
        "text": text,
        "gold": gold,
        "top1": top1,
        "top5": ", ".join(top5),
        "top1_correct": (top1 == gold),
        "top5_correct": (gold in top5),
    })

df = pd.DataFrame(rows)

# 4) Show results
df

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Device set to use cpu

,text,gold,top1,top5,top1_correct,top5_correct
0,Little Red Riding Hood walked into the forest ...,wolf,others,"others, sheriff, rider, girl, horse",False,False
1,The king sat on his [MASK] and spoke to the pe...,throne,throne,"throne, horse, chair, knees, stool",True,True
2,The wizard raised his [MASK] and whispered a s...,staff,hand,"hand, head, hands, sword, voice",False,False
3,The little boy lost his [MASK] in the snow.,hat,life,"life, footing, head, balance, mother",False,False
4,The brave knight drew his [MASK] to fight the ...,sword,sword,"sword, swords, blade, dagger, weapon",True,True
5,The witch offered a poisoned [MASK] to the girl.,apple,drink,"drink, apple, cup, stone, stick",False,True
6,The princess opened the old [MASK] and looked ...,door,door,"door, book, box, window, chest",True,True
7,The giant lived at the top of the tall [MASK].,tower,tower,"tower, mountain, building, tree, hill",True,True
8,The fairy waved her [MASK] and the room sparkled.,wand,hand,"hand, wand, arms, hands, arm",False,True
9,The rabbit ran so fast that the [MASK] could n...,turtle,dog,"dog, horse, wolf, cat, bird",False,False

In [5]:
# AUSWERTUNG

top1 = df["top1_correct"].sum()
top5 = df["top5_correct"].sum()
total = len(df)

print("BERT – Children’s Books Evaluation")
print(f"Top-1 Accuracy: {top1}/{total}")
print(f"Top-5 Accuracy: {top5}/{total}")

BERT – Children’s Books Evaluation
Top-1 Accuracy: 4/10
Top-5 Accuracy: 6/10

In [6]:
# CODE FÜR ELECTRA
!pip install -q transformers sentencepiece

from transformers import pipeline
import pandas as pd

# 1) Load ELECTRA (GENERATOR) for masked-word prediction
fill_mask = pipeline("fill-mask", model="google/electra-base-generator")

# 2) Children-story style cloze sentences (English)
kids_en = [
    ("Little Red Riding Hood walked into the forest and met the [MASK].", "wolf"),
    ("The king sat on his [MASK] and spoke to the people.", "throne"),
    ("The wizard raised his [MASK] and whispered a spell.", "staff"),
    ("The little boy lost his [MASK] in the snow.", "hat"),
    ("The brave knight drew his [MASK] to fight the dragon.", "sword"),
    ("The witch offered a poisoned [MASK] to the girl.", "apple"),
    ("The princess opened the old [MASK] and looked inside.", "door"),
    ("The giant lived at the top of the tall [MASK].", "tower"),
    ("The fairy waved her [MASK] and the room sparkled.", "wand"),
    ("The rabbit ran so fast that the [MASK] could not catch up.", "turtle"),
]

# 3) Run evaluation
rows = []
for text, gold in kids_en:
    preds = fill_mask(text)
    top5 = [p["token_str"].strip() for p in preds[:5]]
    top1 = top5[0]

    rows.append({
        "text": text,
        "gold": gold,
        "top1": top1,
        "top5": ", ".join(top5),
        "top1_correct": (top1 == gold),
        "top5_correct": (gold in top5),
    })

df = pd.DataFrame(rows)

# 4) Show detailed results table
df

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

config.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/135M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/135M [00:00<?, ?B/s]

Device set to use cpu

,text,gold,top1,top5,top1_correct,top5_correct
0,Little Red Riding Hood walked into the forest ...,wolf,sun,"sun, trees, forest, wind, sky",False,False
1,The king sat on his [MASK] and spoke to the pe...,throne,throne,"throne, bed, back, knees, side",True,True
2,The wizard raised his [MASK] and whispered a s...,staff,head,"head, hand, voice, hands, sword",False,False
3,The little boy lost his [MASK] in the snow.,hat,footing,"footing, head, spot, life, body",False,False
4,The brave knight drew his [MASK] to fight the ...,sword,sword,"sword, swords, spear, chariot, bow",True,True
5,The witch offered a poisoned [MASK] to the girl.,apple,potion,"potion, drink, tea, dish, poison",False,False
6,The princess opened the old [MASK] and looked ...,door,door,"door, window, box, book, doors",True,True
7,The giant lived at the top of the tall [MASK].,tower,building,"building, tower, tree, grass, structure",False,True
8,The fairy waved her [MASK] and the room sparkled.,wand,hand,"hand, wand, goodbye, off, away",False,True
9,The rabbit ran so fast that the [MASK] could n...,turtle,rabbit,"rabbit, rabbits, dog, animal, squirrel",False,False

In [7]:
# AUSWERTUNG
top1 = df["top1_correct"].sum()
top5 = df["top5_correct"].sum()
total = len(df)

print("ELECTRA (generator) – Children’s Books Evaluation")
print(f"Top-1 Accuracy: {top1}/{total}")
print(f"Top-5 Accuracy: {top5}/{total}")

ELECTRA (generator) – Children’s Books Evaluation
Top-1 Accuracy: 3/10
Top-5 Accuracy: 5/10

In [19]:
# CODE FÜR mBERT
!pip -q install transformers sentencepiece

from transformers import pipeline
import pandas as pd
import re, unicodedata

fill_mask = pipeline("fill-mask", model="bert-base-multilingual-cased")

def norm(s: str) -> str:
    s = unicodedata.normalize("NFKC", s)
    s = re.sub(r"\s+", " ", s.strip().lower())
    return s

# English children-story style cloze sentences for mBERT
# Each item: (text_with_[MASK], set_of_acceptable_answers)
kids_en = [
    ("Little Red Riding Hood walked into the forest and met the [MASK].", {"wolf"}),
    ("The king sat on his [MASK] and spoke to the people.", {"throne"}),
    ("The wizard raised his [MASK] and whispered a spell.", {"staff"}),
    ("The little boy lost his [MASK] in the snow.", {"hat"}),
    ("The brave knight drew his [MASK] to fight the dragon.", {"sword"}),
    ("The witch offered a poisoned [MASK] to the girl.", {"apple"}),
    ("The princess opened the old [MASK] and looked inside.", {"door"}),
    ("The giant lived at the top of the tall [MASK].", {"tower"}),
    ("The fairy waved her [MASK] and the room sparkled.", {"wand"}),
    ("The rabbit ran so fast that the [MASK] could not catch up.", {"turtle"}),
]

rows = []
for text, gold_set in kids_en:
    preds = fill_mask(text)[:5]
    top5_raw = [p["token_str"] for p in preds]
    top5 = [norm(t) for t in top5_raw]
    top1 = top5[0] if top5 else ""

    gold_norm = {norm(g) for g in gold_set}

    rows.append({
        "text": text,
        "acceptable_answers": ", ".join(sorted(gold_norm)),
        "top1": top5_raw[0] if top5_raw else "",
        "top5": ", ".join(top5_raw),
        "top1_correct": top1 in gold_norm,
        "top5_correct": any(t in gold_norm for t in top5),
    })

df = pd.DataFrame(rows)
display(df)

print("mBERT – Kids (English)")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cpu

,text,acceptable_answers,top1,top5,top1_correct,top5_correct
0,Little Red Riding Hood walked into the forest ...,wolf,forest,"forest, horses, horse, bird, birds",False,False
1,The king sat on his [MASK] and spoke to the pe...,throne,throne,"throne, hands, feet, king, head",True,True
2,The wizard raised his [MASK] and whispered a s...,staff,hands,"hands, hand, eyes, arms, voice",False,False
3,The little boy lost his [MASK] in the snow.,hat,life,"life, mind, son, memory, soul",False,False
4,The brave knight drew his [MASK] to fight the ...,sword,sword,"sword, dragon, horse, blood, wings",True,True
5,The witch offered a poisoned [MASK] to the girl.,apple,bone,"bone, child, girl, soul, woman",False,False
6,The princess opened the old [MASK] and looked ...,door,door,"door, doors, window, room, .",True,True
7,The giant lived at the top of the tall [MASK].,tower,tree,"tree, trees, tall, hill, .",False,False
8,The fairy waved her [MASK] and the room sparkled.,wand,",",",, over, arms, ##s, and",False,False
9,The rabbit ran so fast that the [MASK] could n...,turtle,birds,"birds, legs, animals, eyes, horses",False,False

mBERT – Kids (English)
Top-1: 3 / 10
Top-5: 3 / 10

In [10]:
# Code für RoBERTa
!pip install -q transformers sentencepiece

from transformers import pipeline
import pandas as pd

# 1) Load RoBERTa for masked-word prediction (English)
fill_mask = pipeline("fill-mask", model="roberta-base")

# 2) Children-story style cloze sentences (English)
kids_en = [
    ("Little Red Riding Hood walked into the forest and met the <mask>.", "wolf"),
    ("The king sat on his <mask> and spoke to the people.", "throne"),
    ("The wizard raised his <mask> and whispered a spell.", "staff"),
    ("The little boy lost his <mask> in the snow.", "hat"),
    ("The brave knight drew his <mask> to fight the dragon.", "sword"),
    ("The witch offered a poisoned <mask> to the girl.", "apple"),
    ("The princess opened the old <mask> and looked inside.", "door"),
    ("The giant lived at the top of the tall <mask>.", "tower"),
    ("The fairy waved her <mask> and the room sparkled.", "wand"),
    ("The rabbit ran so fast that the <mask> could not catch up.", "turtle"),
]

# 3) Run evaluation
rows = []
for text, gold in kids_en:
    preds = fill_mask(text)  # list of dicts
    top5 = [p["token_str"].strip() for p in preds[:5]]
    top1 = top5[0]

    rows.append({
        "text": text,
        "gold": gold,
        "top1": top1,
        "top5": ", ".join(top5),
        "top1_correct": (top1.lower() == gold.lower()),
        "top5_correct": (gold.lower() in [t.lower() for t in top5]),
    })

df = pd.DataFrame(rows)
df

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Device set to use cpu

,text,gold,top1,top5,top1_correct,top5_correct
0,Little Red Riding Hood walked into the forest ...,wolf,wolves,"wolves, bears, heroes, giants, bear",False,False
1,The king sat on his <mask> and spoke to the pe...,throne,throne,"throne, horse, knees, feet, seat",True,True
2,The wizard raised his <mask> and whispered a s...,staff,hand,"hand, wand, voice, hands, head",False,False
3,The little boy lost his <mask> in the snow.,hat,shoe,"shoe, footing, hat, shoes, coat",False,True
4,The brave knight drew his <mask> to fight the ...,sword,sword,"sword, swords, shield, spear, blade",True,True
5,The witch offered a poisoned <mask> to the girl.,apple,potion,"potion, apple, drink, dagger, sword",False,True
6,The princess opened the old <mask> and looked ...,door,door,"door, box, coffin, palace, castle",True,True
7,The giant lived at the top of the tall <mask>.,tower,tower,"tower, building, tree, mountain, hill",True,True
8,The fairy waved her <mask> and the room sparkled.,wand,wand,"wand, hand, hands, arms, wings",True,True
9,The rabbit ran so fast that the <mask> could n...,turtle,dog,"dog, squirrel, cat, humans, man",False,False

In [11]:
top1 = int(df["top1_correct"].sum())
top5 = int(df["top5_correct"].sum())
total = len(df)

print("RoBERTa – Children’s Books (English)")
print(f"Top-1 Accuracy: {top1}/{total}")
print(f"Top-5 Accuracy: {top5}/{total}")

RoBERTa – Children’s Books (English)
Top-1 Accuracy: 5/10
Top-5 Accuracy: 7/10

In [19]:
#CODE FÜR MPNET
!pip install -q transformers sentencepiece

from transformers import pipeline
import pandas as pd
fill_mask = pipeline("fill-mask", model="microsoft/mpnet-base")
kids_en = [
    ("Little Red Riding Hood walked into the forest and met the <mask>.", "wolf"),
    ("The king sat on his <mask> and spoke to the people.", "throne"),
    ("The wizard raised his <mask> and whispered a spell.", "staff"),
    ("The little boy lost his <mask> in the snow.", "hat"),
    ("The brave knight drew his <mask> to fight the dragon.", "sword"),
    ("The witch offered a poisoned <mask> to the girl.", "apple"),
    ("The princess opened the old <mask> and looked inside.", "door"),
    ("The giant lived at the top of the tall <mask>.", "tower"),
    ("The fairy waved her <mask> and the room sparkled.", "wand"),
    ("The rabbit ran so fast that the <mask> could not catch up.", "turtle"),
]
rows = []

for text, gold in kids_en:
    preds = fill_mask(text)
    top5 = [p["token_str"].strip() for p in preds[:5]]
    top1 = top5[0]

    rows.append({
        "text": text,
        "gold": gold,
        "top1": top1,
        "top5": ", ".join(top5),
        "top1_correct": top1.lower() == gold.lower(),
        "top5_correct": gold.lower() in [t.lower() for t in top5],
    })

df = pd.DataFrame(rows)
df

config.json:   0%|          | 0.00/493 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/532M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cpu

,text,gold,top1,top5,top1_correct,top5_correct
0,Little Red Riding Hood walked into the forest ...,wolf,wolf,"wolf, prince, forest, witch, king",True,True
1,The king sat on his <mask> and spoke to the pe...,throne,throne,"throne, knees, horse, stool, lap",True,True
2,The wizard raised his <mask> and whispered a s...,staff,wand,"wand, hand, head, voice, hands",False,False
3,The little boy lost his <mask> in the snow.,hat,leg,"leg, mother, father, foot, shoe",False,False
4,The brave knight drew his <mask> to fight the ...,sword,sword,"sword, blade, weapon, bow, swords",True,True
5,The witch offered a poisoned <mask> to the girl.,apple,drink,"drink, apple, potion, pill, egg",False,True
6,The princess opened the old <mask> and looked ...,door,door,"door, box, coffin, case, house",True,True
7,The giant lived at the top of the tall <mask>.,tower,mountain,"mountain, tower, tree, hill, building",False,True
8,The fairy waved her <mask> and the room sparkled.,wand,wand,"wand, hand, hands, wings, arms",True,True
9,The rabbit ran so fast that the <mask> could n...,turtle,dog,"dog, rabbit, elephant, cat, mouse",False,False

In [20]:
top1 = df["top1_correct"].sum()
top5 = df["top5_correct"].sum()

print("MPNet – Children’s Books")
print(f"Top-1 Accuracy: {top1}/10")
print(f"Top-5 Accuracy: {top5}/10")

MPNet – Children’s Books
Top-1 Accuracy: 5/10
Top-5 Accuracy: 7/10

In [21]:
#CODE FÜR ALBERT
!pip install -q transformers sentencepiece

from transformers import pipeline
import pandas as pd

# 1) Load ALBERT for masked-word prediction
fill_mask = pipeline("fill-mask", model="albert-base-v2")

# 2) 10 children-story style cloze sentences (English)
kids_en = [
    ("Little Red Riding Hood walked into the forest and met the [MASK].", "wolf"),
    ("The king sat on his [MASK] and spoke to the people.", "throne"),
    ("The wizard raised his [MASK] and whispered a spell.", "staff"),
    ("The little boy lost his [MASK] in the snow.", "hat"),
    ("The brave knight drew his [MASK] to fight the dragon.", "sword"),
    ("The witch offered a poisoned [MASK] to the girl.", "apple"),
    ("The princess opened the old [MASK] and looked inside.", "door"),
    ("The giant lived at the top of the tall [MASK].", "tower"),
    ("The fairy waved her [MASK] and the room sparkled.", "wand"),
    ("The rabbit ran so fast that the [MASK] could not catch up.", "turtle"),
]

# 3) Run evaluation
rows = []
for text, gold in kids_en:
    preds = fill_mask(text)
    top5 = [p["token_str"].strip() for p in preds[:5]]
    top1 = top5[0]

    rows.append({
        "text": text,
        "gold": gold,
        "top1": top1,
        "top5": ", ".join(top5),
        "top1_correct": top1.lower() == gold.lower(),
        "top5_correct": gold.lower() in [t.lower() for t in top5],
    })

df = pd.DataFrame(rows)
df

config.json:   0%|          | 0.00/684 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/47.4M [00:00<?, ?B/s]

Some weights of the model checkpoint at albert-base-v2 were not used when initializing AlbertForMaskedLM: ['albert.pooler.bias', 'albert.pooler.weight']
- This IS expected if you are initializing AlbertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing AlbertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/760k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.31M [00:00<?, ?B/s]

Device set to use cpu

,text,gold,top1,top5,top1_correct,top5_correct
0,Little Red Riding Hood walked into the forest ...,wolf,argonauts,"argonauts, sun, elves, wolves, sheriff",False,False
1,The king sat on his [MASK] and spoke to the pe...,throne,throne,"throne, chariot, verandah, horseback, bench",True,True
2,The wizard raised his [MASK] and whispered a s...,staff,eyebrow,"eyebrow, voice, hand, wand, sword",False,False
3,The little boy lost his [MASK] in the snow.,hat,virginity,"virginity, eyes, composure, breath, eye",False,False
4,The brave knight drew his [MASK] to fight the ...,sword,sword,"sword, dagger, swords, crossbow, axe",True,True
5,The witch offered a poisoned [MASK] to the girl.,apple,potion,"potion, dagger, knife, flask, spell",False,False
6,The princess opened the old [MASK] and looked ...,door,door,"door, coffin, doors, house, gate",True,True
7,The giant lived at the top of the tall [MASK].,tower,staircase,"staircase, stairs, slab, ladder, tree",False,False
8,The fairy waved her [MASK] and the room sparkled.,wand,hand,"hand, wand, flag, hands, attention",False,True
9,The rabbit ran so fast that the [MASK] could n...,turtle,rabbit,"rabbit, squirrel, mouse, runner, horse",False,False

In [22]:
top1 = int(df["top1_correct"].sum())
top5 = int(df["top5_correct"].sum())
total = len(df)

print("ALBERT – Children’s Books (English)")
print(f"Top-1 Accuracy: {top1}/{total}")
print(f"Top-5 Accuracy: {top5}/{total}")

ALBERT – Children’s Books (English)
Top-1 Accuracy: 3/10
Top-5 Accuracy: 4/10

In [22]:
# CODE FÜR HUMAN
import pandas as pd
import re
import unicodedata

def norm(s):
    s = unicodedata.normalize("NFKC", s)
    return re.sub(r"\s+", " ", s.strip().lower())

# Sentences + gold answers
kids_en = [
    ("Little Red Riding Hood walked into the forest and met the [MASK].", {"wolf"}),
    ("The king sat on his [MASK] and spoke to the people.", {"throne"}),
    ("The wizard raised his [MASK] and whispered a spell.", {"staff"}),
    ("The little boy lost his [MASK] in the snow.", {"hat"}),
    ("The brave knight drew his [MASK] to fight the dragon.", {"sword"}),
    ("The witch offered a poisoned [MASK] to the girl.", {"apple"}),
    ("The princess opened the old [MASK] and looked inside.", {"door"}),
    ("The giant lived at the top of the tall [MASK].", {"tower"}),
    ("The fairy waved her [MASK] and the room sparkled.", {"wand"}),
    ("The rabbit ran so fast that the [MASK] could not catch up.", {"turtle"}),
]

# MODE: "demo" or "manual"
MODE = "demo"

# Fill only if MODE = "manual"
human_answers = [
    {"human_top1": "", "human_top5": []},
    {"human_top1": "", "human_top5": []},
    {"human_top1": "", "human_top5": []},
    {"human_top1": "", "human_top5": []},
    {"human_top1": "", "human_top5": []},
    {"human_top1": "", "human_top5": []},
    {"human_top1": "", "human_top5": []},
    {"human_top1": "", "human_top5": []},
    {"human_top1": "", "human_top5": []},
    {"human_top1": "", "human_top5": []},
]

rows = []

for i, (text, gold_set) in enumerate(kids_en):
    gold_norm = {norm(g) for g in gold_set}

    if MODE == "demo":
        top1 = list(gold_norm)[0]
        top5 = list(gold_norm)
    else:
        top1 = norm(human_answers[i]["human_top1"])
        top5 = [norm(x) for x in human_answers[i]["human_top5"]]

    rows.append({
        "text": text,
        "gold": ", ".join(gold_norm),
        "human_top1": top1,
        "human_top5": ", ".join(top5),
        "top1_correct": top1 in gold_norm,
        "top5_correct": any(t in gold_norm for t in top5),
    })

df = pd.DataFrame(rows)
display(df)

print("HUMAN – Kids English")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

,text,gold,human_top1,human_top5,top1_correct,top5_correct
0,Little Red Riding Hood walked into the forest ...,wolf,wolf,wolf,True,True
1,The king sat on his [MASK] and spoke to the pe...,throne,throne,throne,True,True
2,The wizard raised his [MASK] and whispered a s...,staff,staff,staff,True,True
3,The little boy lost his [MASK] in the snow.,hat,hat,hat,True,True
4,The brave knight drew his [MASK] to fight the ...,sword,sword,sword,True,True
5,The witch offered a poisoned [MASK] to the girl.,apple,apple,apple,True,True
6,The princess opened the old [MASK] and looked ...,door,door,door,True,True
7,The giant lived at the top of the tall [MASK].,tower,tower,tower,True,True
8,The fairy waved her [MASK] and the room sparkled.,wand,wand,wand,True,True
9,The rabbit ran so fast that the [MASK] could n...,turtle,turtle,turtle,True,True

HUMAN – Kids English
Top-1: 10 / 10
Top-5: 10 / 10

In [20]:
# WIKIPEDIA

In [24]:
#CODE FÜR BERT
!pip -q install transformers sentencepiece requests

import re, requests, pandas as pd
from transformers import pipeline

fill = pipeline("fill-mask", model="bert-base-uncased")

titles = ["Berlin","Water","Earth","Photosynthesis","Machine_learning",
          "Python_(programming_language)","Albert_Einstein","World_War_II",
          "Solar_System","DNA"]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def wiki_first_sentence(title):
    j = requests.get(f"https://en.wikipedia.org/api/rest_v1/page/summary/{title}",
                     headers={"User-Agent":"kaggle-bert-wiki/1.0"}).json()
    sent = re.split(r"(?<=[.!?])\s+", j["extract"].strip())[0]
    return sent, j.get("revision"), j["content_urls"]["desktop"]["page"]

def make_mask(sent):
    for w in re.findall(r"[A-Za-z]+", sent):
        wl = w.lower()
        if wl in STOP or len(wl) < 4: 
            continue
        if len(fill.tokenizer.tokenize(wl)) != 1: 
            continue
        return wl, re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sent, count=1)
    return None, None

rows = []
for t in titles:
    sent, rev, url = wiki_first_sentence(t)
    gold, masked = make_mask(sent)
    preds = fill(masked)[:5]
    top5 = [p["token_str"].strip().lower() for p in preds]
    rows.append({
        "title": t, "revision": rev, "url": url,
        "masked_sentence": masked, "gold": gold,
        "top1": top5[0], "top5": ", ".join(top5),
        "top1_correct": top5[0]==gold, "top5_correct": gold in top5
    })

df = pd.DataFrame(rows)
display(df[["title","revision","url","masked_sentence","gold","top1","top5_correct"]])

print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cpu

,title,revision,url,masked_sentence,gold,top1,top5_correct
0,Berlin,1329770155,https://en.wikipedia.org/wiki/Berlin,"[MASK] is the capital of Germany, as well as i...",berlin,berlin,True
1,Water,1330280139,https://en.wikipedia.org/wiki/Water,[MASK] is an inorganic compound with the chemi...,water,it,False
2,Earth,1330154980,https://en.wikipedia.org/wiki/Earth,[MASK] is the third planet from the Sun and th...,earth,it,False
3,Photosynthesis,1328455398,https://en.wikipedia.org/wiki/Photosynthesis,Photosynthesis is a [MASK] of biological proce...,system,group,False
4,Machine_learning,1329075091,https://en.wikipedia.org/wiki/Machine_learning,[MASK] learning (ML) is a field of study in ar...,machine,machine,True
5,Python_(programming_language),1328469413,https://en.wikipedia.org/wiki/Python_(programm...,"[MASK] is a high-level, general-purpose progra...",python,it,True
6,Albert_Einstein,1329760122,https://en.wikipedia.org/wiki/Albert_Einstein,[MASK] Einstein was a German-born theoretical ...,albert,albert,True
7,World_War_II,1330288894,https://en.wikipedia.org/wiki/World_War_II,[MASK] War II or the Second World War was a gl...,world,world,True
8,Solar_System,1330143767,https://en.wikipedia.org/wiki/Solar_System,The [MASK] System \nis the gravitationally bou...,solar,solar,True
9,DNA,1329082382,https://en.wikipedia.org/wiki/DNA,Deoxyribonucleic [MASK] is a polymer composed ...,acid,acid,True

Top-1: 6 / 10
Top-5: 7 / 10

In [25]:
#CODE FÜR ELECTRA
!pip -q install transformers sentencepiece requests

import re, requests, pandas as pd
from transformers import pipeline

fill = pipeline("fill-mask", model="google/electra-base-generator")

titles = ["Berlin","Water","Earth","Photosynthesis","Machine_learning",
          "Python_(programming_language)","Albert_Einstein","World_War_II",
          "Solar_System","DNA"]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def wiki_first_sentence(title):
    j = requests.get(f"https://en.wikipedia.org/api/rest_v1/page/summary/{title}",
                     headers={"User-Agent":"kaggle-electra-wiki/1.0"}).json()
    sent = re.split(r"(?<=[.!?])\s+", j["extract"].strip())[0]
    return sent, j.get("revision"), j["content_urls"]["desktop"]["page"]

def make_mask(sent):
    for w in re.findall(r"[A-Za-z]+", sent):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        return wl, re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sent, count=1)
    return None, None

rows = []
for t in titles:
    sent, rev, url = wiki_first_sentence(t)
    gold, masked = make_mask(sent)
    preds = fill(masked)[:5]
    top5 = [p["token_str"].strip().lower() for p in preds]
    rows.append({
        "title": t, "revision": rev, "url": url,
        "masked_sentence": masked, "gold": gold,
        "top1": top5[0], "top5": ", ".join(top5),
        "top1_correct": top5[0]==gold, "top5_correct": gold in top5
    })

df = pd.DataFrame(rows)
display(df[["title","revision","url","masked_sentence","gold","top1","top5_correct"]])

print("ELECTRA (generator) Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("ELECTRA (generator) Top-5:", int(df.top5_correct.sum()), "/", len(df))

Device set to use cpu

,title,revision,url,masked_sentence,gold,top1,top5_correct
0,Berlin,1329770155,https://en.wikipedia.org/wiki/Berlin,"[MASK] is the capital of Germany, as well as i...",berlin,it,True
1,Water,1330280139,https://en.wikipedia.org/wiki/Water,[MASK] is an inorganic compound with the chemi...,water,it,False
2,Earth,1330154980,https://en.wikipedia.org/wiki/Earth,[MASK] is the third planet from the Sun and th...,earth,it,True
3,Photosynthesis,1328455398,https://en.wikipedia.org/wiki/Photosynthesis,Photosynthesis is a [MASK] of biological proce...,system,system,True
4,Machine_learning,1329075091,https://en.wikipedia.org/wiki/Machine_learning,[MASK] learning (ML) is a field of study in ar...,machine,artificial,True
5,Python_(programming_language),1328469413,https://en.wikipedia.org/wiki/Python_(programm...,"[MASK] is a high-level, general-purpose progra...",python,it,True
6,Albert_Einstein,1329760122,https://en.wikipedia.org/wiki/Albert_Einstein,[MASK] Einstein was a German-born theoretical ...,albert,albert,True
7,World_War_II,1330288894,https://en.wikipedia.org/wiki/World_War_II,[MASK] War II or the Second World War was a gl...,world,world,True
8,Solar_System,1330143767,https://en.wikipedia.org/wiki/Solar_System,The [MASK] System \nis the gravitationally bou...,solar,solar,True
9,DNA,1329082382,https://en.wikipedia.org/wiki/DNA,Deoxyribonucleic [MASK] is a polymer composed ...,acid,acid,True

ELECTRA (generator) Top-1: 5 / 10
ELECTRA (generator) Top-5: 9 / 10

In [18]:
# CODE FÜR MBERT

!pip -q install transformers sentencepiece requests

import re, requests, pandas as pd
from transformers import pipeline

fill = pipeline("fill-mask", model="bert-base-multilingual-cased")

titles = ["Berlin","Water","Earth","Photosynthesis","Machine_learning",
          "Python_(programming_language)","Albert_Einstein","World_War_II",
          "Solar_System","DNA"]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def wiki_first_sentence(title):
    url = f"https://en.wikipedia.org/api/rest_v1/page/summary/{title}"
    r = requests.get(url, headers={"User-Agent":"kaggle-mbert-enwiki/1.0"}, timeout=30)
    if r.status_code != 200:
        return None, None, None, f"http_{r.status_code}"
    j = r.json()
    if "extract" not in j or "content_urls" not in j or not j["extract"].strip():
        return None, None, None, "no_extract"
    sent = re.split(r"(?<=[.!?])\s+", j["extract"].strip())[0]
    rev = j.get("revision", None)
    page_url = j["content_urls"]["desktop"]["page"]
    return sent, rev, page_url, ""

def make_mask(sent):
    for w in re.findall(r"[A-Za-z]+", sent):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        # single-token constraint for THIS model (mBERT)
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sent, count=1)
        return wl, masked
    return None, None

rows = []
for t in titles:
    sent, rev, url, err = wiki_first_sentence(t)

    if err:
        rows.append({
            "title": t, "revision": rev, "url": url,
            "masked_sentence": "", "gold": "",
            "top1": "", "top5": "",
            "top1_correct": False, "top5_correct": False,
            "error": err
        })
        continue

    gold, masked = make_mask(sent)
    if not gold:
        rows.append({
            "title": t, "revision": rev, "url": url,
            "masked_sentence": sent, "gold": "",
            "top1": "", "top5": "",
            "top1_correct": False, "top5_correct": False,
            "error": "no_single_token_word_found"
        })
        continue

    preds = fill(masked)[:5]
    top5 = [p["token_str"].strip().lower() for p in preds]
    top1 = top5[0] if top5 else ""

    rows.append({
        "title": t, "revision": rev, "url": url,
        "masked_sentence": masked, "gold": gold,
        "top1": top1, "top5": ", ".join(top5),
        "top1_correct": (top1 == gold),
        "top5_correct": (gold in top5),
        "error": ""
    })

df = pd.DataFrame(rows)
display(df[["title","revision","url","masked_sentence","gold","top1","top5_correct","error"]])

print("mBERT – Wikipedia (EN)")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cpu

,title,revision,url,masked_sentence,gold,top1,top5_correct,error
0,Berlin,1330692226,https://en.wikipedia.org/wiki/Berlin,"Berlin is the [MASK] of Germany, as well as it...",capital,capital,True,
1,Water,1330280139,https://en.wikipedia.org/wiki/Water,[MASK] is an inorganic compound with the chemi...,water,the,False,
2,Earth,1330585631,https://en.wikipedia.org/wiki/Earth,[MASK] is the third planet from the Sun and th...,earth,earth,True,
3,Photosynthesis,1328455398,https://en.wikipedia.org/wiki/Photosynthesis,Photosynthesis is a [MASK] of biological proce...,system,process,True,
4,Machine_learning,1330613401,https://en.wikipedia.org/wiki/Machine_learning,[MASK] learning (ML) is a field of study in ar...,machine,machine,True,
5,Python_(programming_language),1328469413,https://en.wikipedia.org/wiki/Python_(programm...,"Python is a [MASK]-level, general-purpose prog...",high,top,True,
6,Albert_Einstein,1330674479,https://en.wikipedia.org/wiki/Albert_Einstein,Albert Einstein was a [MASK]-born theoretical ...,german,einstein,True,
7,World_War_II,1330365110,https://en.wikipedia.org/wiki/World_War_II,[MASK] War II or the Second World War was a gl...,world,world,True,
8,Solar_System,1330539128,https://en.wikipedia.org/wiki/Solar_System,The [MASK] System \nis the gravitationally bou...,solar,solar,True,
9,DNA,1329082382,https://en.wikipedia.org/wiki/DNA,Deoxyribonucleic [MASK] is a polymer composed ...,acid,acid,True,

mBERT – Wikipedia (EN)
Top-1: 6 / 10
Top-5: 9 / 10

In [3]:
# CODE FÜR RoBERTa
!pip -q install transformers sentencepiece requests

import re, requests, pandas as pd
from transformers import pipeline

fill = pipeline("fill-mask", model="roberta-base")

titles = ["Berlin","Water","Earth","Photosynthesis","Machine_learning",
          "Python_(programming_language)","Albert_Einstein","World_War_II",
          "Solar_System","DNA"]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def wiki_first_sentence(title):
    j = requests.get(f"https://en.wikipedia.org/api/rest_v1/page/summary/{title}",
                     headers={"User-Agent":"kaggle-roberta-wiki/1.0"}).json()
    sent = re.split(r"(?<=[.!?])\s+", j["extract"].strip())[0]
    return sent, j.get("revision"), j["content_urls"]["desktop"]["page"]

def make_mask(sent):
    for w in re.findall(r"[A-Za-z]+", sent):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        # single-token constraint for exact-match fairness
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "<mask>", sent, count=1)
        return wl, masked
    return None, None

rows = []
for t in titles:
    sent, rev, url = wiki_first_sentence(t)
    gold, masked = make_mask(sent)
    preds = fill(masked)[:5]
    top5 = [p["token_str"].strip().lower() for p in preds]
    rows.append({
        "title": t, "revision": rev, "url": url,
        "masked_sentence": masked, "gold": gold,
        "top1": top5[0], "top5": ", ".join(top5),
        "top1_correct": top5[0]==gold, "top5_correct": gold in top5
    })

df = pd.DataFrame(rows)
display(df[["title","revision","url","masked_sentence","gold","top1","top5_correct"]])

print("RoBERTa – Wikipedia (EN)")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Device set to use cpu

,title,revision,url,masked_sentence,gold,top1,top5_correct
0,Berlin,1329770155,https://en.wikipedia.org/wiki/Berlin,"Berlin is the <mask> of Germany, as well as it...",capital,capital,True
1,Water,1330280139,https://en.wikipedia.org/wiki/Water,<mask> is an inorganic compound with the chemi...,water,it,False
2,Earth,1330154980,https://en.wikipedia.org/wiki/Earth,<mask> is the third planet from the Sun and th...,earth,earth,True
3,Photosynthesis,1328455398,https://en.wikipedia.org/wiki/Photosynthesis,Photosynthesis is a <mask> of biological proce...,system,series,False
4,Machine_learning,1329075091,https://en.wikipedia.org/wiki/Machine_learning,<mask> learning (ML) is a field of study in ar...,machine,machine,True
5,Python_(programming_language),1328469413,https://en.wikipedia.org/wiki/Python_(programm...,"<mask> is a high-level, general-purpose progra...",python,python,True
6,Albert_Einstein,1329760122,https://en.wikipedia.org/wiki/Albert_Einstein,Albert Einstein was a German-<mask> theoretica...,born,born,True
7,World_War_II,1330365110,https://en.wikipedia.org/wiki/World_War_II,<mask> War II or the Second World War was a gl...,world,world,True
8,Solar_System,1330143767,https://en.wikipedia.org/wiki/Solar_System,The Solar <mask> \nis the gravitationally boun...,system,system,True
9,DNA,1329082382,https://en.wikipedia.org/wiki/DNA,Deoxyribonucleic <mask> is a polymer composed ...,acid,acid,True

RoBERTa – Wikipedia (EN)
Top-1: 8 / 10
Top-5: 8 / 10

In [4]:
# CODE FÜR MPNET
!pip -q install transformers sentencepiece requests

import re, requests, pandas as pd
from transformers import pipeline

# Load MPNet
fill = pipeline("fill-mask", model="microsoft/mpnet-base")

# English Wikipedia article titles
titles = [
    "Berlin", "Water", "Earth", "Photosynthesis",
    "Machine_learning", "Python_(programming_language)",
    "Albert_Einstein", "World_War_II", "Solar_System", "DNA"
]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def wiki_first_sentence(title):
    r = requests.get(
        f"https://en.wikipedia.org/api/rest_v1/page/summary/{title}",
        headers={"User-Agent": "kaggle-mpnet-wiki/1.0"}
    ).json()
    sent = re.split(r"(?<=[.!?])\s+", r["extract"].strip())[0]
    return sent, r.get("revision"), r["content_urls"]["desktop"]["page"]

def make_mask(sentence):
    for w in re.findall(r"[A-Za-z]+", sentence):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        return wl, re.sub(rf"\b{re.escape(w)}\b", "<mask>", sentence, count=1)
    return None, None

rows = []
for t in titles:
    sent, rev, url = wiki_first_sentence(t)
    gold, masked = make_mask(sent)
    preds = fill(masked)[:5]
    top5 = [p["token_str"].strip().lower() for p in preds]
    rows.append({
        "title": t,
        "revision": rev,
        "url": url,
        "masked_sentence": masked,
        "gold": gold,
        "top1": top5[0],
        "top5": ", ".join(top5),
        "top1_correct": top5[0] == gold,
        "top5_correct": gold in top5
    })

df = pd.DataFrame(rows)
display(df[["title","revision","url","masked_sentence","gold","top1","top5_correct"]])

print("MPNet – Wikipedia")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

config.json:   0%|          | 0.00/493 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/532M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cpu

,title,revision,url,masked_sentence,gold,top1,top5_correct
0,Berlin,1329770155,https://en.wikipedia.org/wiki/Berlin,"<mask> is the capital of Germany, as well as i...",berlin,berlin,True
1,Water,1330280139,https://en.wikipedia.org/wiki/Water,<mask> is an inorganic compound with the chemi...,water,it,False
2,Earth,1330154980,https://en.wikipedia.org/wiki/Earth,<mask> is the third planet from the Sun and th...,earth,pluto,False
3,Photosynthesis,1328455398,https://en.wikipedia.org/wiki/Photosynthesis,Photosynthesis is a <mask> of biological proce...,system,set,True
4,Machine_learning,1329075091,https://en.wikipedia.org/wiki/Machine_learning,<mask> learning (ML) is a field of study in ar...,machine,machine,True
5,Python_(programming_language),1328469413,https://en.wikipedia.org/wiki/Python_(programm...,"<mask> is a high-level, general-purpose progra...",python,c,True
6,Albert_Einstein,1329760122,https://en.wikipedia.org/wiki/Albert_Einstein,<mask> Einstein was a German-born theoretical ...,albert,albert,True
7,World_War_II,1330365110,https://en.wikipedia.org/wiki/World_War_II,<mask> War II or the Second World War was a gl...,world,world,True
8,Solar_System,1330143767,https://en.wikipedia.org/wiki/Solar_System,The <mask> System \nis the gravitationally bou...,solar,solar,True
9,DNA,1329082382,https://en.wikipedia.org/wiki/DNA,Deoxyribonucleic <mask> is a polymer composed ...,acid,acid,True

MPNet – Wikipedia
Top-1: 6 / 10
Top-5: 8 / 10

In [5]:
# CODE FÜR ALBERT
!pip -q install transformers sentencepiece requests

import re, requests, pandas as pd
from transformers import pipeline

fill = pipeline("fill-mask", model="albert-base-v2")

titles = ["Berlin","Water","Earth","Photosynthesis","Machine_learning",
          "Python_(programming_language)","Albert_Einstein","World_War_II",
          "Solar_System","DNA"]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def wiki_first_sentence(title):
    j = requests.get(f"https://en.wikipedia.org/api/rest_v1/page/summary/{title}",
                     headers={"User-Agent":"kaggle-albert-wiki/1.0"}).json()
    sent = re.split(r"(?<=[.!?])\s+", j["extract"].strip())[0]
    return sent, j.get("revision"), j["content_urls"]["desktop"]["page"]

def make_mask(sent):
    for w in re.findall(r"[A-Za-z]+", sent):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        return wl, re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sent, count=1)
    return None, None

rows = []
for t in titles:
    sent, rev, url = wiki_first_sentence(t)
    gold, masked = make_mask(sent)
    preds = fill(masked)[:5]
    top5 = [p["token_str"].strip().lower() for p in preds]
    rows.append({
        "title": t, "revision": rev, "url": url,
        "masked_sentence": masked, "gold": gold,
        "top1": top5[0], "top5": ", ".join(top5),
        "top1_correct": top5[0]==gold, "top5_correct": gold in top5
    })

df = pd.DataFrame(rows)
display(df[["title","revision","url","masked_sentence","gold","top1","top5_correct"]])

print("ALBERT – Wikipedia (EN)")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

config.json:   0%|          | 0.00/684 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/47.4M [00:00<?, ?B/s]

Some weights of the model checkpoint at albert-base-v2 were not used when initializing AlbertForMaskedLM: ['albert.pooler.bias', 'albert.pooler.weight']
- This IS expected if you are initializing AlbertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing AlbertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/760k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.31M [00:00<?, ?B/s]

Device set to use cpu

,title,revision,url,masked_sentence,gold,top1,top5_correct
0,Berlin,1329770155,https://en.wikipedia.org/wiki/Berlin,"[MASK] is the capital of Germany, as well as i...",berlin,frankfurt,False
1,Water,1330280139,https://en.wikipedia.org/wiki/Water,[MASK] is an inorganic compound with the chemi...,water,lithium,False
2,Earth,1330154980,https://en.wikipedia.org/wiki/Earth,[MASK] is the third planet from the Sun and th...,earth,jupiter,False
3,Photosynthesis,1328455398,https://en.wikipedia.org/wiki/Photosynthesis,Photosynthesis is a [MASK] of biological proce...,system,sequence,False
4,Machine_learning,1329075091,https://en.wikipedia.org/wiki/Machine_learning,[MASK] learning (ML) is a field of study in ar...,machine,stochastic,False
5,Python_(programming_language),1328469413,https://en.wikipedia.org/wiki/Python_(programm...,"[MASK] is a high-level, general-purpose progra...",python,unicode,True
6,Albert_Einstein,1329760122,https://en.wikipedia.org/wiki/Albert_Einstein,[MASK] Einstein was a German-born theoretical ...,albert,albert,True
7,World_War_II,1330365110,https://en.wikipedia.org/wiki/World_War_II,[MASK] War II or the Second World War was a gl...,world,world,True
8,Solar_System,1330143767,https://en.wikipedia.org/wiki/Solar_System,The [MASK] System \nis the gravitationally bou...,solar,solar,True
9,DNA,1329082382,https://en.wikipedia.org/wiki/DNA,Deoxyribonucleic [MASK] is a polymer composed ...,acid,acid,True

ALBERT – Wikipedia (EN)
Top-1: 4 / 10
Top-5: 5 / 10

In [16]:
# CODE FÜR HUMAN
!pip -q install transformers sentencepiece requests pandas

import re, requests, pandas as pd
from transformers import AutoTokenizer

# Use ALBERT tokenizer ONLY so the masked word selection is EXACTLY like your ALBERT code
tok = AutoTokenizer.from_pretrained("albert-base-v2")

titles = ["Berlin","Water","Earth","Photosynthesis","Machine_learning",
          "Python_(programming_language)","Albert_Einstein","World_War_II",
          "Solar_System","DNA"]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def wiki_first_sentence(title):
    j = requests.get(
        f"https://en.wikipedia.org/api/rest_v1/page/summary/{title}",
        headers={"User-Agent":"kaggle-human-wiki/1.0"},
        timeout=30
    ).json()
    sent = re.split(r"(?<=[.!?])\s+", j["extract"].strip())[0]
    return sent, j.get("revision"), j["content_urls"]["desktop"]["page"]

def make_mask_same_as_albert(sent):
    # SAME rule as your ALBERT code:
    # - skip stopwords/short words
    # - only accept single-token words under ALBERT tokenizer
    for w in re.findall(r"[A-Za-z]+", sent):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        if len(tok.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sent, count=1)
        return wl, masked
    return None, None

def norm_word(x):
    # robust: compare only letters
    return re.sub(r"[^a-z]", "", str(x).lower().strip())

# 1) Build the SAME 10 masked sentences + gold labels
items = []
for t in titles:
    try:
        sent, rev, url = wiki_first_sentence(t)
        gold, masked = make_mask_same_as_albert(sent)

        if not gold:
            items.append({
                "title": t, "revision": rev, "url": url,
                "masked_sentence": "", "gold": "", "error": "no_single_token_word_found"
            })
        else:
            items.append({
                "title": t, "revision": rev, "url": url,
                "masked_sentence": masked, "gold": gold, "error": ""
            })

    except Exception as e:
        items.append({
            "title": t, "revision": None, "url": "",
            "masked_sentence": "", "gold": "", "error": repr(e)
        })

df_items = pd.DataFrame(items)

# Show prompts for humans (DON'T show gold when collecting answers)
display(df_items[["title","revision","url","masked_sentence","error"]])

# 2) HUMAN answers
# Set MODE="demo" once to verify scoring works (it will fill top1 with gold)
MODE = "demo"   # change to "manual" when you enter real answers

human_answers = [
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
]

# 3) Score humans (always /10)
rows = []
for i, row in df_items.iterrows():
    gold = norm_word(row["gold"])

    if MODE == "demo":
        top1 = gold
        top5 = [gold]
    else:
        top1 = norm_word(human_answers[i].get("human_top1",""))
        top5 = [norm_word(x) for x in human_answers[i].get("human_top5", [])]
        top5 = [x for x in top5 if x]

    if gold == "" or row["masked_sentence"] == "":
        rows.append({**row,
                     "human_top1": top1,
                     "human_top5": ", ".join(top5),
                     "top1_correct": False,
                     "top5_correct": False})
        continue

    rows.append({**row,
                 "human_top1": top1,
                 "human_top5": ", ".join(top5),
                 "top1_correct": (top1 == gold),
                 "top5_correct": (gold in top5) if top5 else False})

df_human = pd.DataFrame(rows)
display(df_human[["title","url","gold","human_top1","top1_correct","top5_correct","error"]])

print("\nHUMAN – Wikipedia (EN) – same sentences as ALBERT setup")
print("Top-1:", int(df_human.top1_correct.sum()), "/", len(df_human))
print("Top-5:", int(df_human.top5_correct.sum()), "/", len(df_human))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

,title,revision,url,masked_sentence,error
0,Berlin,1330692226,https://en.wikipedia.org/wiki/Berlin,"[MASK] is the capital of Germany, as well as i...",
1,Water,1330280139,https://en.wikipedia.org/wiki/Water,[MASK] is an inorganic compound with the chemi...,
2,Earth,1330585631,https://en.wikipedia.org/wiki/Earth,[MASK] is the third planet from the Sun and th...,
3,Photosynthesis,1328455398,https://en.wikipedia.org/wiki/Photosynthesis,Photosynthesis is a [MASK] of biological proce...,
4,Machine_learning,1330613401,https://en.wikipedia.org/wiki/Machine_learning,[MASK] learning (ML) is a field of study in ar...,
5,Python_(programming_language),1328469413,https://en.wikipedia.org/wiki/Python_(programm...,"[MASK] is a high-level, general-purpose progra...",
6,Albert_Einstein,1330674479,https://en.wikipedia.org/wiki/Albert_Einstein,[MASK] Einstein was a German-born theoretical ...,
7,World_War_II,1330365110,https://en.wikipedia.org/wiki/World_War_II,[MASK] War II or the Second World War was a gl...,
8,Solar_System,1330539128,https://en.wikipedia.org/wiki/Solar_System,The [MASK] System \nis the gravitationally bou...,
9,DNA,1329082382,https://en.wikipedia.org/wiki/DNA,Deoxyribonucleic [MASK] is a polymer composed ...,

,title,url,gold,human_top1,top1_correct,top5_correct,error
0,Berlin,https://en.wikipedia.org/wiki/Berlin,berlin,berlin,True,True,
1,Water,https://en.wikipedia.org/wiki/Water,water,water,True,True,
2,Earth,https://en.wikipedia.org/wiki/Earth,earth,earth,True,True,
3,Photosynthesis,https://en.wikipedia.org/wiki/Photosynthesis,system,system,True,True,
4,Machine_learning,https://en.wikipedia.org/wiki/Machine_learning,machine,machine,True,True,
5,Python_(programming_language),https://en.wikipedia.org/wiki/Python_(programm...,python,python,True,True,
6,Albert_Einstein,https://en.wikipedia.org/wiki/Albert_Einstein,albert,albert,True,True,
7,World_War_II,https://en.wikipedia.org/wiki/World_War_II,world,world,True,True,
8,Solar_System,https://en.wikipedia.org/wiki/Solar_System,solar,solar,True,True,
9,DNA,https://en.wikipedia.org/wiki/DNA,acid,acid,True,True,

HUMAN – Wikipedia (EN) – same sentences as ALBERT setup
Top-1: 10 / 10
Top-5: 10 / 10

In [ ]:
# DEUTSCHE TEXTE

In [8]:
# CODE FÜR BERT

!pip -q install transformers sentencepiece requests beautifulsoup4 lxml

import re, requests, pandas as pd
from bs4 import BeautifulSoup
from transformers import pipeline

fill = pipeline("fill-mask", model="bert-base-german-cased")

# 10 echte deutsche Texte auf Wikisource (Grimm, Public Domain)
pages = [
    "Rothkäppchen_(1812)",
    "Aschenputtel_(1812)",
    "Hänsel_und_Gretel_(1812)",
    "Rumpelstilzchen_(1812)",
    "Sneewittchen_(Schneeweißchen)_(1812)",
    "Rothkäppchen_(1837)",
    "Aschenputtel_(1857)",
    "Rumpelstilzchen_(1819)",
    "Sneewittchen_(1857)",
    "Hänsel_und_Grethel_(1840)",
]

BASE = "https://de.wikisource.org"
API  = f"{BASE}/w/api.php"

STOP = set("der die das und oder aber wenn dann ist sind war waren von mit auf in für als bei über unter im am an des dem den".split())

def get_plain_text_from_wikisource(title):
    # MediaWiki Action API: parse -> HTML; then strip tags
    params = {
        "action": "parse",
        "page": title,
        "prop": "text",
        "format": "json",
        "formatversion": "2",
    }
    r = requests.get(API, params=params, headers={"User-Agent":"kaggle-de-bert/1.0"}, timeout=25)
    r.raise_for_status()
    j = r.json()

    html = j["parse"]["text"]
    rev  = j["parse"].get("revid", None)
    url  = f"{BASE}/wiki/{title}"

    soup = BeautifulSoup(html, "lxml")
    text = soup.get_text(" ", strip=True)
    text = re.sub(r"\s+", " ", text)
    return text, rev, url

def first_good_sentence(text):
    sents = [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if len(s.strip()) > 50]
    return sents[0] if sents else None

def make_mask(sent):
    for w in re.findall(r"[A-Za-zÄÖÜäöüß]+", sent):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        if len(fill.tokenizer.tokenize(wl)) != 1:   # fairness: single-token target
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sent, count=1)
        return wl, masked
    return None, None

rows = []
skipped = []

for title in pages:
    try:
        text, rev, url = get_plain_text_from_wikisource(title)
        sent = first_good_sentence(text)
        if not sent:
            skipped.append((title, "no_sentence"))
            continue

        gold, masked = make_mask(sent)
        if gold is None:
            skipped.append((title, "no_single_token_word_found"))
            continue

        preds = fill(masked)[:5]
        top5 = [p["token_str"].strip().lower() for p in preds]
        rows.append({
            "title": title, "revision": rev, "url": url,
            "masked_sentence": masked, "gold": gold,
            "top1": top5[0], "top5": ", ".join(top5),
            "top1_correct": top5[0] == gold,
            "top5_correct": gold in top5
        })
    except Exception as e:
        skipped.append((title, repr(e)))

df = pd.DataFrame(rows)
display(df[["title","revision","url","masked_sentence","gold","top1","top5_correct"]])

print("German BERT – Deutsche Texte (Wikisource)")
print("Built items:", len(df), "/", len(pages))
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

print("\nSkipped (falls welche):")
for s in skipped:
    print("-", s)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Some weights of the model checkpoint at bert-base-german-cased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cpu

,title,revision,url,masked_sentence,gold,top1,top5_correct
0,Rothkäppchen_(1812),None,https://de.wikisource.org/wiki/Rothkäppchen_(1...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,von,False
1,Aschenputtel_(1812),None,https://de.wikisource.org/wiki/Aschenputtel_(1...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,von,False
2,Hänsel_und_Gretel_(1812),None,https://de.wikisource.org/wiki/Hänsel_und_Gret...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,von,False
3,Rumpelstilzchen_(1812),None,https://de.wikisource.org/wiki/Rumpelstilzchen...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,von,False
4,Sneewittchen_(Schneeweißchen)_(1812),None,https://de.wikisource.org/wiki/Sneewittchen_(S...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,von,False
5,Rothkäppchen_(1837),None,https://de.wikisource.org/wiki/Rothkäppchen_(1...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,von,False
6,Aschenputtel_(1857),None,https://de.wikisource.org/wiki/Aschenputtel_(1...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,von,False
7,Rumpelstilzchen_(1819),None,https://de.wikisource.org/wiki/Rumpelstilzchen...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,von,False
8,Sneewittchen_(1857),None,https://de.wikisource.org/wiki/Sneewittchen_(1...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,von,False
9,Hänsel_und_Grethel_(1840),None,https://de.wikisource.org/wiki/Hänsel_und_Gret...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,von,False

German BERT – Deutsche Texte (Wikisource)
Built items: 10 / 10
Top-1: 0 / 10
Top-5: 0 / 10

Skipped (falls welche):

In [10]:
# CODE FÜR ELECTRA
!pip -q install transformers sentencepiece requests beautifulsoup4 lxml

import re, requests, pandas as pd
from bs4 import BeautifulSoup
from transformers import pipeline

# German ELECTRA generator (masked LM)
fill = pipeline("fill-mask", model="deepset/gelectra-base-generator")

# EXACTLY the same 10 pages as before
pages = [
    "Rothkäppchen_(1812)",
    "Aschenputtel_(1812)",
    "Hänsel_und_Gretel_(1812)",
    "Rumpelstilzchen_(1812)",
    "Sneewittchen_(1812)",
    "Frau_Holle_(1812)",
    "Der_Froschkönig_oder_der_eiserne_Heinrich_(1812)",
    "Die_sieben_Raben_(1812)",
    "Dornröschen_(1812)",
    "Der_Tapfere_Schneiderlein_(1812)",
]

BASE = "https://de.wikisource.org"
API  = f"{BASE}/w/api.php"

STOP = set("der die das und oder aber wenn dann ist sind war waren von mit auf in für als bei über unter im am an des dem den".split())

def get_plain_text(title):
    params = {"action":"parse","page":title,"prop":"text","format":"json","formatversion":"2"}
    r = requests.get(API, params=params, headers={"User-Agent":"kaggle-electra-de/1.0"}, timeout=25)
    r.raise_for_status()
    j = r.json()

    html = j["parse"]["text"]
    rev  = j["parse"].get("revid", None)
    url  = f"{BASE}/wiki/{title}"

    soup = BeautifulSoup(html, "lxml")
    text = re.sub(r"\s+", " ", soup.get_text(" ", strip=True))
    return text, rev, url

def pick_sentences(text, max_sents=50):
    sents = [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if len(s.strip()) > 60]
    return sents[:max_sents]

def make_mask(sent):
    for w in re.findall(r"[A-Za-zÄÖÜäöüß]+", sent):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        # exact-match only makes sense for single-token targets
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sent, count=1)
        return wl, masked
    return None, None

rows = []

for title in pages:
    url = f"{BASE}/wiki/{title}"
    rev = None

    try:
        text, rev, url = get_plain_text(title)

        chosen = None
        for s in pick_sentences(text, max_sents=50):
            gold, masked = make_mask(s)
            if gold is not None:
                chosen = (gold, masked)
                break

        if chosen is None:
            # IMPORTANT: still count this item (as incorrect), so denominator stays 10
            rows.append({
                "title": title, "revision": rev, "url": url,
                "masked_sentence": "", "gold": "",
                "top1": "", "top5": "",
                "top1_correct": False, "top5_correct": False,
                "error": "no_single_token_word_found"
            })
            continue

        gold, masked = chosen
        preds = fill(masked)[:5]
        top5 = [p["token_str"].strip().lower() for p in preds]
        top1 = top5[0] if top5 else ""

        rows.append({
            "title": title, "revision": rev, "url": url,
            "masked_sentence": masked, "gold": gold,
            "top1": top1, "top5": ", ".join(top5),
            "top1_correct": top1 == gold,
            "top5_correct": gold in top5,
            "error": ""
        })

    except Exception as e:
        # IMPORTANT: still count this item (as incorrect)
        rows.append({
            "title": title, "revision": rev, "url": url,
            "masked_sentence": "", "gold": "",
            "top1": "", "top5": "",
            "top1_correct": False, "top5_correct": False,
            "error": repr(e)
        })

df = pd.DataFrame(rows)
display(df[["title","revision","url","masked_sentence","gold","top1","top5_correct","error"]])

print("ELECTRA (DE generator) – German texts (Wikisource)")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))  # ALWAYS /10
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))  # ALWAYS /10

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Device set to use cpu

,title,revision,url,masked_sentence,gold,top1,top5_correct,error
0,Rothkäppchen_(1812),None,https://de.wikisource.org/wiki/Rothkäppchen_(1...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,verlag,True,
1,Aschenputtel_(1812),None,https://de.wikisource.org/wiki/Aschenputtel_(1...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,verlag,True,
2,Hänsel_und_Gretel_(1812),None,https://de.wikisource.org/wiki/Hänsel_und_Gret...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,verlag,True,
3,Rumpelstilzchen_(1812),None,https://de.wikisource.org/wiki/Rumpelstilzchen...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,verlag,True,
4,Sneewittchen_(1812),None,https://de.wikisource.org/wiki/Sneewittchen_(1...,,,,False,KeyError('parse')
5,Frau_Holle_(1812),None,https://de.wikisource.org/wiki/Frau_Holle_(1812),Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,verlag,True,
6,Der_Froschkönig_oder_der_eiserne_Heinrich_(1812),None,https://de.wikisource.org/wiki/Der_Froschkönig...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,titel,True,
7,Die_sieben_Raben_(1812),None,https://de.wikisource.org/wiki/Die_sieben_Rabe...,,,,False,KeyError('parse')
8,Dornröschen_(1812),None,https://de.wikisource.org/wiki/Dornröschen_(1812),Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,verlag,True,
9,Der_Tapfere_Schneiderlein_(1812),None,https://de.wikisource.org/wiki/Der_Tapfere_Sch...,,,,False,KeyError('parse')

ELECTRA (DE generator) – German texts (Wikisource)
Top-1: 0 / 10
Top-5: 7 / 10

In [2]:
# CODE FÜR MBERT
!pip -q install transformers sentencepiece requests beautifulsoup4 lxml

import re, requests, pandas as pd
from bs4 import BeautifulSoup
from transformers import pipeline

# mBERT
fill = pipeline("fill-mask", model="bert-base-multilingual-cased")

# gleiche 10 Seiten wie vorher
pages = [
    "Rothkäppchen_(1812)",
    "Aschenputtel_(1812)",
    "Hänsel_und_Gretel_(1812)",
    "Rumpelstilzchen_(1812)",
    "Sneewittchen_(1812)",
    "Frau_Holle_(1812)",
    "Der_Froschkönig_oder_der_eiserne_Heinrich_(1812)",
    "Die_sieben_Raben_(1812)",
    "Dornröschen_(1812)",
    "Der_Tapfere_Schneiderlein_(1812)",
]

BASE = "https://de.wikisource.org"
API  = f"{BASE}/w/api.php"

STOP = set("der die das und oder aber wenn dann ist sind war waren von mit auf in für als bei über unter im am an des dem den".split())

def get_plain_text(title):
    params = {"action":"parse","page":title,"prop":"text","format":"json","formatversion":"2"}
    r = requests.get(API, params=params, headers={"User-Agent":"kaggle-mbert-de/1.0"}, timeout=25)
    r.raise_for_status()
    j = r.json()

    html = j["parse"]["text"]
    rev  = j["parse"].get("revid", None)
    url  = f"{BASE}/wiki/{title}"

    soup = BeautifulSoup(html, "lxml")
    text = re.sub(r"\s+", " ", soup.get_text(" ", strip=True))
    return text, rev, url

def pick_sentences(text, max_sents=50):
    sents = [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if len(s.strip()) > 60]
    return sents[:max_sents]

def make_mask(sent):
    for w in re.findall(r"[A-Za-zÄÖÜäöüß]+", sent):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        # fair: nur single-token targets
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sent, count=1)
        return wl, masked
    return None, None

rows = []

for title in pages:
    url = f"{BASE}/wiki/{title}"
    rev = None

    try:
        text, rev, url = get_plain_text(title)

        chosen = None
        for s in pick_sentences(text, max_sents=50):
            gold, masked = make_mask(s)
            if gold is not None:
                chosen = (gold, masked)
                break

        if chosen is None:
            # trotzdem zählen -> immer 10
            rows.append({
                "title": title, "revision": rev, "url": url,
                "masked_sentence": "", "gold": "",
                "top1": "", "top5": "",
                "top1_correct": False, "top5_correct": False,
                "error": "no_single_token_word_found"
            })
            continue

        gold, masked = chosen
        preds = fill(masked)[:5]
        top5 = [p["token_str"].strip().lower() for p in preds]
        top1 = top5[0] if top5 else ""

        rows.append({
            "title": title, "revision": rev, "url": url,
            "masked_sentence": masked, "gold": gold,
            "top1": top1, "top5": ", ".join(top5),
            "top1_correct": top1 == gold,
            "top5_correct": gold in top5,
            "error": ""
        })

    except Exception as e:
        # trotzdem zählen -> immer 10
        rows.append({
            "title": title, "revision": rev, "url": url,
            "masked_sentence": "", "gold": "",
            "top1": "", "top5": "",
            "top1_correct": False, "top5_correct": False,
            "error": repr(e)
        })

df = pd.DataFrame(rows)
display(df[["title","revision","url","masked_sentence","gold","top1","top5_correct","error"]])

print("mBERT – German texts (Wikisource)")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))  # immer /10
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))  # immer /10

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cpu

,title,revision,url,masked_sentence,gold,top1,top5_correct,error
0,Rothkäppchen_(1812),None,https://de.wikisource.org/wiki/Rothkäppchen_(1...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,:,True,
1,Aschenputtel_(1812),None,https://de.wikisource.org/wiki/Aschenputtel_(1...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,:,True,
2,Hänsel_und_Gretel_(1812),None,https://de.wikisource.org/wiki/Hänsel_und_Gret...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,familie,False,
3,Rumpelstilzchen_(1812),None,https://de.wikisource.org/wiki/Rumpelstilzchen...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,:,True,
4,Sneewittchen_(1812),None,https://de.wikisource.org/wiki/Sneewittchen_(1...,,,,False,KeyError('parse')
5,Frau_Holle_(1812),None,https://de.wikisource.org/wiki/Frau_Holle_(1812),Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,:,True,
6,Der_Froschkönig_oder_der_eiserne_Heinrich_(1812),None,https://de.wikisource.org/wiki/Der_Froschkönig...,Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,:,False,
7,Die_sieben_Raben_(1812),None,https://de.wikisource.org/wiki/Die_sieben_Rabe...,,,,False,KeyError('parse')
8,Dornröschen_(1812),None,https://de.wikisource.org/wiki/Dornröschen_(1812),Textdaten <<< >>> [MASK]: Brüder Grimm Illustr...,autor,:,True,
9,Der_Tapfere_Schneiderlein_(1812),None,https://de.wikisource.org/wiki/Der_Tapfere_Sch...,,,,False,KeyError('parse')

mBERT – German texts (Wikisource)
Top-1: 0 / 10
Top-5: 5 / 10

In [3]:
# CODE FÜR RoBERTA
!pip -q install transformers sentencepiece requests beautifulsoup4 lxml

import re, requests, pandas as pd
from bs4 import BeautifulSoup
from transformers import pipeline

# XLM-RoBERTa (multilingual RoBERTa) for German
fill = pipeline("fill-mask", model="xlm-roberta-base")

pages = [
    "Rothkäppchen_(1812)",
    "Aschenputtel_(1812)",
    "Hänsel_und_Gretel_(1812)",
    "Rumpelstilzchen_(1812)",
    "Sneewittchen_(1812)",
    "Frau_Holle_(1812)",
    "Der_Froschkönig_oder_der_eiserne_Heinrich_(1812)",
    "Die_sieben_Raben_(1812)",
    "Dornröschen_(1812)",
    "Der_Tapfere_Schneiderlein_(1812)",
]

BASE = "https://de.wikisource.org"
API  = f"{BASE}/w/api.php"

STOP = set("der die das und oder aber wenn dann ist sind war waren von mit auf in für als bei über unter im am an des dem den".split())

def get_plain_text(title):
    params = {"action":"parse","page":title,"prop":"text","format":"json","formatversion":"2"}
    r = requests.get(API, params=params, headers={"User-Agent":"kaggle-xlmr-de/1.0"}, timeout=25)
    r.raise_for_status()
    j = r.json()

    html = j["parse"]["text"]
    rev  = j["parse"].get("revid", None)
    url  = f"{BASE}/wiki/{title}"

    soup = BeautifulSoup(html, "lxml")
    text = re.sub(r"\s+", " ", soup.get_text(" ", strip=True))
    return text, rev, url

def pick_sentences(text, max_sents=50):
    sents = [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if len(s.strip()) > 60]
    return sents[:max_sents]

def make_mask(sent):
    for w in re.findall(r"[A-Za-zÄÖÜäöüß]+", sent):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        # single-token target constraint
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "<mask>", sent, count=1)
        return wl, masked
    return None, None

rows = []
for title in pages:
    url = f"{BASE}/wiki/{title}"
    rev = None

    try:
        text, rev, url = get_plain_text(title)

        chosen = None
        for s in pick_sentences(text, max_sents=50):
            gold, masked = make_mask(s)
            if gold is not None:
                chosen = (gold, masked)
                break

        if chosen is None:
            rows.append({
                "title": title, "revision": rev, "url": url,
                "masked_sentence": "", "gold": "",
                "top1": "", "top5": "",
                "top1_correct": False, "top5_correct": False,
                "error": "no_single_token_word_found"
            })
            continue

        gold, masked = chosen
        preds = fill(masked)[:5]
        top5 = [p["token_str"].strip().lower() for p in preds]
        top1 = top5[0] if top5 else ""

        rows.append({
            "title": title, "revision": rev, "url": url,
            "masked_sentence": masked, "gold": gold,
            "top1": top1, "top5": ", ".join(top5),
            "top1_correct": top1 == gold,
            "top5_correct": gold in top5,
            "error": ""
        })

    except Exception as e:
        rows.append({
            "title": title, "revision": rev, "url": url,
            "masked_sentence": "", "gold": "",
            "top1": "", "top5": "",
            "top1_correct": False, "top5_correct": False,
            "error": repr(e)
        })

df = pd.DataFrame(rows)
display(df[["title","revision","url","masked_sentence","gold","top1","top5_correct","error"]])

print("XLM-RoBERTa – German texts (Wikisource)")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

Some weights of the model checkpoint at xlm-roberta-base were not used when initializing XLMRobertaForMaskedLM: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing XLMRobertaForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

Device set to use cpu

,title,revision,url,masked_sentence,gold,top1,top5_correct,error
0,Rothkäppchen_(1812),None,https://de.wikisource.org/wiki/Rothkäppchen_(1...,Textdaten <<< >>> <mask>: Brüder Grimm Illustr...,autor,autor,True,
1,Aschenputtel_(1812),None,https://de.wikisource.org/wiki/Aschenputtel_(1...,Textdaten <<< >>> <mask>: Brüder Grimm Illustr...,autor,titel,True,
2,Hänsel_und_Gretel_(1812),None,https://de.wikisource.org/wiki/Hänsel_und_Gret...,Textdaten <<< >>> <mask>: Brüder Grimm Illustr...,autor,titel,True,
3,Rumpelstilzchen_(1812),None,https://de.wikisource.org/wiki/Rumpelstilzchen...,Textdaten <<< >>> <mask>: Brüder Grimm Illustr...,autor,autor,True,
4,Sneewittchen_(1812),None,https://de.wikisource.org/wiki/Sneewittchen_(1...,,,,False,KeyError('parse')
5,Frau_Holle_(1812),None,https://de.wikisource.org/wiki/Frau_Holle_(1812),Textdaten <<< >>> <mask>: Brüder Grimm Illustr...,autor,verlag,True,
6,Der_Froschkönig_oder_der_eiserne_Heinrich_(1812),None,https://de.wikisource.org/wiki/Der_Froschkönig...,Textdaten <<< >>> <mask>: Brüder Grimm Illustr...,autor,autor,True,
7,Die_sieben_Raben_(1812),None,https://de.wikisource.org/wiki/Die_sieben_Rabe...,,,,False,KeyError('parse')
8,Dornröschen_(1812),None,https://de.wikisource.org/wiki/Dornröschen_(1812),Textdaten <<< >>> <mask>: Brüder Grimm Illustr...,autor,autor,True,
9,Der_Tapfere_Schneiderlein_(1812),None,https://de.wikisource.org/wiki/Der_Tapfere_Sch...,,,,False,KeyError('parse')

XLM-RoBERTa – German texts (Wikisource)
Top-1: 4 / 10
Top-5: 7 / 10

In [4]:
# CODE FÜR MPNET
!pip -q install transformers sentencepiece requests beautifulsoup4 lxml

import re, requests, pandas as pd
from bs4 import BeautifulSoup
from transformers import pipeline

# MPNet (English MLM). Works with <mask>, but is NOT German-specialized.
fill = pipeline("fill-mask", model="microsoft/mpnet-base")

pages = [
    "Rothkäppchen_(1812)",
    "Aschenputtel_(1812)",
    "Hänsel_und_Gretel_(1812)",
    "Rumpelstilzchen_(1812)",
    "Sneewittchen_(1812)",
    "Frau_Holle_(1812)",
    "Der_Froschkönig_oder_der_eiserne_Heinrich_(1812)",
    "Die_sieben_Raben_(1812)",
    "Dornröschen_(1812)",
    "Der_Tapfere_Schneiderlein_(1812)",
]

BASE = "https://de.wikisource.org"
API  = f"{BASE}/w/api.php"

STOP = set("der die das und oder aber wenn dann ist sind war waren von mit auf in für als bei über unter im am an des dem den".split())

def get_plain_text(title):
    params = {"action":"parse","page":title,"prop":"text","format":"json","formatversion":"2"}
    r = requests.get(API, params=params, headers={"User-Agent":"kaggle-mpnet-de/1.0"}, timeout=25)
    r.raise_for_status()
    j = r.json()

    html = j["parse"]["text"]
    rev  = j["parse"].get("revid", None)
    url  = f"{BASE}/wiki/{title}"

    soup = BeautifulSoup(html, "lxml")
    text = re.sub(r"\s+", " ", soup.get_text(" ", strip=True))
    return text, rev, url

def pick_sentences(text, max_sents=50):
    sents = [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if len(s.strip()) > 60]
    return sents[:max_sents]

def make_mask(sent):
    for w in re.findall(r"[A-Za-zÄÖÜäöüß]+", sent):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "<mask>", sent, count=1)
        return wl, masked
    return None, None

rows = []
for title in pages:
    url = f"{BASE}/wiki/{title}"
    rev = None

    try:
        text, rev, url = get_plain_text(title)

        chosen = None
        for s in pick_sentences(text, max_sents=50):
            gold, masked = make_mask(s)
            if gold is not None:
                chosen = (gold, masked)
                break

        if chosen is None:
            rows.append({
                "title": title, "revision": rev, "url": url,
                "masked_sentence": "", "gold": "",
                "top1": "", "top5": "",
                "top1_correct": False, "top5_correct": False,
                "error": "no_single_token_word_found"
            })
            continue

        gold, masked = chosen
        preds = fill(masked)[:5]
        top5 = [p["token_str"].strip().lower() for p in preds]
        top1 = top5[0] if top5 else ""

        rows.append({
            "title": title, "revision": rev, "url": url,
            "masked_sentence": masked, "gold": gold,
            "top1": top1, "top5": ", ".join(top5),
            "top1_correct": top1 == gold,
            "top5_correct": gold in top5,
            "error": ""
        })

    except Exception as e:
        rows.append({
            "title": title, "revision": rev, "url": url,
            "masked_sentence": "", "gold": "",
            "top1": "", "top5": "",
            "top1_correct": False, "top5_correct": False,
            "error": repr(e)
        })

df = pd.DataFrame(rows)
display(df[["title","revision","url","masked_sentence","gold","top1","top5_correct","error"]])

print("MPNet – German texts (Wikisource) [NOTE: MPNet is EN-trained]")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

config.json:   0%|          | 0.00/493 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/532M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cpu

,title,revision,url,masked_sentence,gold,top1,top5_correct,error
0,Rothkäppchen_(1812),None,https://de.wikisource.org/wiki/Rothkäppchen_(1...,Textdaten <<< >>> Autor: Brüder <mask> Illustr...,grimm,:,False,
1,Aschenputtel_(1812),None,https://de.wikisource.org/wiki/Aschenputtel_(1...,Textdaten <<< >>> Autor: Brüder <mask> Illustr...,grimm,:,False,
2,Hänsel_und_Gretel_(1812),None,https://de.wikisource.org/wiki/Hänsel_und_Gret...,Textdaten <<< >>> Autor: Brüder <mask> Illustr...,grimm,:,False,
3,Rumpelstilzchen_(1812),None,https://de.wikisource.org/wiki/Rumpelstilzchen...,Textdaten <<< >>> Autor: Brüder <mask> Illustr...,grimm,:,False,
4,Sneewittchen_(1812),None,https://de.wikisource.org/wiki/Sneewittchen_(1...,,,,False,KeyError('parse')
5,Frau_Holle_(1812),None,https://de.wikisource.org/wiki/Frau_Holle_(1812),Textdaten <<< >>> Autor: Brüder <mask> Illustr...,grimm,:,False,
6,Der_Froschkönig_oder_der_eiserne_Heinrich_(1812),None,https://de.wikisource.org/wiki/Der_Froschkönig...,Textdaten <<< >>> Autor: Brüder <mask> Illustr...,grimm,:,False,
7,Die_sieben_Raben_(1812),None,https://de.wikisource.org/wiki/Die_sieben_Rabe...,,,,False,KeyError('parse')
8,Dornröschen_(1812),None,https://de.wikisource.org/wiki/Dornröschen_(1812),Textdaten <<< >>> Autor: Brüder <mask> Illustr...,grimm,:,False,
9,Der_Tapfere_Schneiderlein_(1812),None,https://de.wikisource.org/wiki/Der_Tapfere_Sch...,,,,False,KeyError('parse')

MPNet – German texts (Wikisource) [NOTE: MPNet is EN-trained]
Top-1: 0 / 10
Top-5: 0 / 10

In [5]:
# CODE FÜR ALBERT
!pip -q install transformers sentencepiece requests beautifulsoup4 lxml

import re, requests, pandas as pd
from bs4 import BeautifulSoup
from transformers import pipeline

# ALBERT (English MLM). Works with [MASK], but is NOT German-specialized.
fill = pipeline("fill-mask", model="albert-base-v2")

pages = [
    "Rothkäppchen_(1812)",
    "Aschenputtel_(1812)",
    "Hänsel_und_Gretel_(1812)",
    "Rumpelstilzchen_(1812)",
    "Sneewittchen_(1812)",
    "Frau_Holle_(1812)",
    "Der_Froschkönig_oder_der_eiserne_Heinrich_(1812)",
    "Die_sieben_Raben_(1812)",
    "Dornröschen_(1812)",
    "Der_Tapfere_Schneiderlein_(1812)",
]

BASE = "https://de.wikisource.org"
API  = f"{BASE}/w/api.php"

STOP = set("der die das und oder aber wenn dann ist sind war waren von mit auf in für als bei über unter im am an des dem den".split())

def get_plain_text(title):
    params = {"action":"parse","page":title,"prop":"text","format":"json","formatversion":"2"}
    r = requests.get(API, params=params, headers={"User-Agent":"kaggle-albert-de/1.0"}, timeout=25)
    r.raise_for_status()
    j = r.json()

    html = j["parse"]["text"]
    rev  = j["parse"].get("revid", None)
    url  = f"{BASE}/wiki/{title}"

    soup = BeautifulSoup(html, "lxml")
    text = re.sub(r"\s+", " ", soup.get_text(" ", strip=True))
    return text, rev, url

def pick_sentences(text, max_sents=50):
    sents = [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if len(s.strip()) > 60]
    return sents[:max_sents]

def make_mask(sent):
    for w in re.findall(r"[A-Za-zÄÖÜäöüß]+", sent):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sent, count=1)
        return wl, masked
    return None, None

rows = []

for title in pages:
    url = f"{BASE}/wiki/{title}"
    rev = None

    try:
        text, rev, url = get_plain_text(title)

        chosen = None
        for s in pick_sentences(text, max_sents=50):
            gold, masked = make_mask(s)
            if gold is not None:
                chosen = (gold, masked)
                break

        if chosen is None:
            rows.append({
                "title": title, "revision": rev, "url": url,
                "masked_sentence": "", "gold": "",
                "top1": "", "top5": "",
                "top1_correct": False, "top5_correct": False,
                "error": "no_single_token_word_found"
            })
            continue

        gold, masked = chosen
        preds = fill(masked)[:5]
        top5 = [p["token_str"].strip().lower() for p in preds]
        top1 = top5[0] if top5 else ""

        rows.append({
            "title": title, "revision": rev, "url": url,
            "masked_sentence": masked, "gold": gold,
            "top1": top1, "top5": ", ".join(top5),
            "top1_correct": top1 == gold,
            "top5_correct": gold in top5,
            "error": ""
        })

    except Exception as e:
        rows.append({
            "title": title, "revision": rev, "url": url,
            "masked_sentence": "", "gold": "",
            "top1": "", "top5": "",
            "top1_correct": False, "top5_correct": False,
            "error": repr(e)
        })

df = pd.DataFrame(rows)
display(df[["title","revision","url","masked_sentence","gold","top1","top5_correct","error"]])

print("ALBERT – German texts (Wikisource) [NOTE: ALBERT is EN-trained]")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

config.json:   0%|          | 0.00/684 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/47.4M [00:00<?, ?B/s]

Some weights of the model checkpoint at albert-base-v2 were not used when initializing AlbertForMaskedLM: ['albert.pooler.bias', 'albert.pooler.weight']
- This IS expected if you are initializing AlbertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing AlbertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/760k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.31M [00:00<?, ?B/s]

Device set to use cpu

,title,revision,url,masked_sentence,gold,top1,top5_correct,error
0,Rothkäppchen_(1812),None,https://de.wikisource.org/wiki/Rothkäppchen_(1...,Textdaten <<< >>> Autor: Brüder [MASK] Illustr...,grimm,];,False,
1,Aschenputtel_(1812),None,https://de.wikisource.org/wiki/Aschenputtel_(1...,Textdaten <<< >>> Autor: Brüder [MASK] Illustr...,grimm,kunst,False,
2,Hänsel_und_Gretel_(1812),None,https://de.wikisource.org/wiki/Hänsel_und_Gret...,Textdaten <<< >>> Autor: Brüder [MASK] Illustr...,grimm,kunst,False,
3,Rumpelstilzchen_(1812),None,https://de.wikisource.org/wiki/Rumpelstilzchen...,Textdaten <<< >>> Autor: Brüder [MASK] Illustr...,grimm,];,False,
4,Sneewittchen_(1812),None,https://de.wikisource.org/wiki/Sneewittchen_(1...,,,,False,KeyError('parse')
5,Frau_Holle_(1812),None,https://de.wikisource.org/wiki/Frau_Holle_(1812),Textdaten <<< >>> Autor: Brüder [MASK] Illustr...,grimm,kunst,False,
6,Der_Froschkönig_oder_der_eiserne_Heinrich_(1812),None,https://de.wikisource.org/wiki/Der_Froschkönig...,Textdaten <<< >>> Autor: Brüder [MASK] Illustr...,grimm,kunst,False,
7,Die_sieben_Raben_(1812),None,https://de.wikisource.org/wiki/Die_sieben_Rabe...,,,,False,KeyError('parse')
8,Dornröschen_(1812),None,https://de.wikisource.org/wiki/Dornröschen_(1812),Textdaten <<< >>> Autor: Brüder [MASK] Illustr...,grimm,kunst,False,
9,Der_Tapfere_Schneiderlein_(1812),None,https://de.wikisource.org/wiki/Der_Tapfere_Sch...,,,,False,KeyError('parse')

ALBERT – German texts (Wikisource) [NOTE: ALBERT is EN-trained]
Top-1: 0 / 10
Top-5: 0 / 10

In [15]:
# CODE FÜR HUMAN
!pip -q install requests beautifulsoup4 lxml pandas

import re, requests, pandas as pd
from bs4 import BeautifulSoup

pages = [
    "Rothkäppchen_(1812)",
    "Aschenputtel_(1812)",
    "Hänsel_und_Gretel_(1812)",
    "Rumpelstilzchen_(1812)",
    "Sneewittchen_(1812)",
    "Frau_Holle_(1812)",
    "Der_Froschkönig_oder_der_eiserne_Heinrich_(1812)",
    "Die_sieben_Raben_(1812)",
    "Dornröschen_(1812)",
    "Der_Tapfere_Schneiderlein_(1812)",
]

BASE = "https://de.wikisource.org"
API  = f"{BASE}/w/api.php"

STOP = set("""
der die das und oder aber wenn dann ist sind war waren von mit auf in für als bei über unter im am an des dem den
ein eine einer eines einem einen
ich du er sie es wir ihr ihnen ihnen mich dich sich
""".split())

def get_plain_text(title):
    params = {"action":"parse","page":title,"prop":"text","format":"json","formatversion":"2"}
    r = requests.get(API, params=params, headers={"User-Agent":"kaggle-human-wikisource/1.0"}, timeout=30)
    r.raise_for_status()
    j = r.json()

    html = j["parse"]["text"]
    rev  = j["parse"].get("revid", None)
    url  = f"{BASE}/wiki/{title}"

    soup = BeautifulSoup(html, "lxml")
    text = re.sub(r"\s+", " ", soup.get_text(" ", strip=True))
    return text, rev, url

def pick_sentences(text, max_sents=60):
    sents = [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if len(s.strip()) > 60]
    return sents[:max_sents]

def make_mask_human(sent):
    # Humans don't need tokenizer constraints; pick a reasonable content word
    # Avoid super-short/stopwords; mask first suitable word
    for w in re.findall(r"[A-Za-zÄÖÜäöüß]+", sent):
        wl = w.lower()
        if wl in STOP or len(wl) < 5:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sent, count=1)
        return wl, masked
    return None, None

def norm_word_de(x):
    # keep only letters incl. German umlauts; lower-case
    return re.sub(r"[^a-zäöüß]", "", str(x).lower().strip())

# -----------------------------
# 1) Build 10 German prompts
# -----------------------------
items = []
for title in pages:
    rev, url = None, f"{BASE}/wiki/{title}"
    try:
        text, rev, url = get_plain_text(title)

        chosen = None
        for s in pick_sentences(text, max_sents=60):
            gold, masked = make_mask_human(s)
            if gold:
                chosen = (gold, masked)
                break

        if chosen is None:
            items.append({
                "title": title, "revision": rev, "url": url,
                "masked_sentence": "", "gold": "", "error": "no_maskable_sentence_found"
            })
        else:
            gold, masked = chosen
            items.append({
                "title": title, "revision": rev, "url": url,
                "masked_sentence": masked, "gold": gold, "error": ""
            })

    except Exception as e:
        items.append({
            "title": title, "revision": rev, "url": url,
            "masked_sentence": "", "gold": "", "error": repr(e)
        })

df_items = pd.DataFrame(items)

# Show prompts for humans (don't show gold when collecting answers!)
display(df_items[["title","revision","url","masked_sentence","error"]])

# -----------------------------
# 2) HUMAN answers
# -----------------------------
# "demo"  -> fills human_top1 with gold so you immediately see scoring works
# "manual"-> you fill the answers below
MODE = "demo"

human_answers = [
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
]

# -----------------------------
# 3) Score humans (always /10)
# -----------------------------
rows = []
for i, row in df_items.iterrows():
    gold = norm_word_de(row["gold"])

    if MODE == "demo":
        top1 = gold
        top5 = [gold]
    else:
        top1 = norm_word_de(human_answers[i].get("human_top1",""))
        top5 = [norm_word_de(x) for x in human_answers[i].get("human_top5", [])]
        top5 = [x for x in top5 if x]

    # keep denominator 10
    if gold == "" or row["masked_sentence"] == "":
        rows.append({**row,
                     "human_top1": top1,
                     "human_top5": ", ".join(top5),
                     "top1_correct": False,
                     "top5_correct": False})
        continue

    rows.append({**row,
                 "human_top1": top1,
                 "human_top5": ", ".join(top5),
                 "top1_correct": (top1 == gold),
                 "top5_correct": (gold in top5) if top5 else False})

df_human = pd.DataFrame(rows)
display(df_human[["title","url","gold","human_top1","top1_correct","top5_correct","error"]])

print("\nHUMAN baseline – German texts (Wikisource)")
print("Top-1:", int(df_human.top1_correct.sum()), "/", len(df_human))
print("Top-5:", int(df_human.top5_correct.sum()), "/", len(df_human))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

,title,revision,url,masked_sentence,error
0,Rothkäppchen_(1812),None,https://de.wikisource.org/wiki/Rothkäppchen_(1...,[MASK] <<< >>> Autor: Brüder Grimm Illustrator...,
1,Aschenputtel_(1812),None,https://de.wikisource.org/wiki/Aschenputtel_(1...,[MASK] <<< >>> Autor: Brüder Grimm Illustrator...,
2,Hänsel_und_Gretel_(1812),None,https://de.wikisource.org/wiki/Hänsel_und_Gret...,[MASK] <<< >>> Autor: Brüder Grimm Illustrator...,
3,Rumpelstilzchen_(1812),None,https://de.wikisource.org/wiki/Rumpelstilzchen...,[MASK] <<< >>> Autor: Brüder Grimm Illustrator...,
4,Sneewittchen_(1812),None,https://de.wikisource.org/wiki/Sneewittchen_(1...,,KeyError('parse')
5,Frau_Holle_(1812),None,https://de.wikisource.org/wiki/Frau_Holle_(1812),[MASK] <<< >>> Autor: Brüder Grimm Illustrator...,
6,Der_Froschkönig_oder_der_eiserne_Heinrich_(1812),None,https://de.wikisource.org/wiki/Der_Froschkönig...,[MASK] <<< >>> Autor: Brüder Grimm Illustrator...,
7,Die_sieben_Raben_(1812),None,https://de.wikisource.org/wiki/Die_sieben_Rabe...,,KeyError('parse')
8,Dornröschen_(1812),None,https://de.wikisource.org/wiki/Dornröschen_(1812),[MASK] <<< >>> Autor: Brüder Grimm Illustrator...,
9,Der_Tapfere_Schneiderlein_(1812),None,https://de.wikisource.org/wiki/Der_Tapfere_Sch...,,KeyError('parse')

,title,url,gold,human_top1,top1_correct,top5_correct,error
0,Rothkäppchen_(1812),https://de.wikisource.org/wiki/Rothkäppchen_(1...,textdaten,textdaten,True,True,
1,Aschenputtel_(1812),https://de.wikisource.org/wiki/Aschenputtel_(1...,textdaten,textdaten,True,True,
2,Hänsel_und_Gretel_(1812),https://de.wikisource.org/wiki/Hänsel_und_Gret...,textdaten,textdaten,True,True,
3,Rumpelstilzchen_(1812),https://de.wikisource.org/wiki/Rumpelstilzchen...,textdaten,textdaten,True,True,
4,Sneewittchen_(1812),https://de.wikisource.org/wiki/Sneewittchen_(1...,,,False,False,KeyError('parse')
5,Frau_Holle_(1812),https://de.wikisource.org/wiki/Frau_Holle_(1812),textdaten,textdaten,True,True,
6,Der_Froschkönig_oder_der_eiserne_Heinrich_(1812),https://de.wikisource.org/wiki/Der_Froschkönig...,textdaten,textdaten,True,True,
7,Die_sieben_Raben_(1812),https://de.wikisource.org/wiki/Die_sieben_Rabe...,,,False,False,KeyError('parse')
8,Dornröschen_(1812),https://de.wikisource.org/wiki/Dornröschen_(1812),textdaten,textdaten,True,True,
9,Der_Tapfere_Schneiderlein_(1812),https://de.wikisource.org/wiki/Der_Tapfere_Sch...,,,False,False,KeyError('parse')

HUMAN baseline – German texts (Wikisource)
Top-1: 7 / 10
Top-5: 7 / 10

In [ ]:
# POPULAR BOOK

In [7]:
# CODE FÜR BERT
!pip -q install transformers sentencepiece requests

import re, requests, pandas as pd
from transformers import pipeline

fill = pipeline("fill-mask", model="bert-base-uncased")

# 10 popular public-domain books (Project Gutenberg plain text)
books = [
    ("Pride and Prejudice", "Jane Austen", "https://www.gutenberg.org/cache/epub/1342/pg1342.txt"),
    ("Alice's Adventures in Wonderland", "Lewis Carroll", "https://www.gutenberg.org/cache/epub/11/pg11.txt"),
    ("Peter Pan", "J. M. Barrie", "https://www.gutenberg.org/cache/epub/16/pg16.txt"),
    ("The Adventures of Sherlock Holmes", "Arthur Conan Doyle", "https://www.gutenberg.org/cache/epub/1661/pg1661.txt"),
    ("The Time Machine", "H. G. Wells", "https://www.gutenberg.org/cache/epub/35/pg35.txt"),
    ("Dracula", "Bram Stoker", "https://www.gutenberg.org/cache/epub/345/pg345.txt"),
    ("Frankenstein", "Mary Wollstonecraft Shelley", "https://www.gutenberg.org/cache/epub/84/pg84.txt"),
    ("A Tale of Two Cities", "Charles Dickens", "https://www.gutenberg.org/cache/epub/98/pg98.txt"),
    ("The Wonderful Wizard of Oz", "L. Frank Baum", "https://www.gutenberg.org/cache/epub/55/pg55.txt"),
    ("Moby-Dick", "Herman Melville", "https://www.gutenberg.org/cache/epub/2701/pg2701.txt"),
]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def clean_gutenberg_text(txt: str) -> str:
    # Try to remove Gutenberg header/footer
    start = re.search(r"\*\*\* START OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    end   = re.search(r"\*\*\* END OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    if start and end and start.end() < end.start():
        txt = txt[start.end():end.start()]
    txt = txt.replace("\r", "\n")
    txt = re.sub(r"\n{2,}", "\n", txt)
    txt = re.sub(r"[ \t]+", " ", txt)
    return txt.strip()

def get_sentences(url: str, max_sents=200):
    raw = requests.get(url, headers={"User-Agent":"kaggle-bert-books/1.0"}, timeout=40).text
    txt = clean_gutenberg_text(raw)
    # Basic sentence split
    sents = [s.strip() for s in re.split(r"(?<=[.!?])\s+", txt) if len(s.strip()) > 60]
    return sents[:max_sents]

def make_mask(sentence: str):
    # choose a single-token content word for exact-match evaluation
    for w in re.findall(r"[A-Za-z]+", sentence):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sentence, count=1)
        return wl, masked
    return None, None

rows = []
for title, author, url in books:
    try:
        sents = get_sentences(url)
        chosen = None
        for s in sents:
            gold, masked = make_mask(s)
            if gold is not None:
                chosen = (gold, masked)
                break

        if chosen is None:
            # still count -> always 10 rows
            rows.append({
                "book": title, "author": author, "source_url": url,
                "masked_sentence": "", "gold": "",
                "top1": "", "top5": "",
                "top1_correct": False, "top5_correct": False,
                "error": "no_single_token_word_found"
            })
            continue

        gold, masked = chosen
        preds = fill(masked)[:5]
        top5 = [p["token_str"].strip().lower() for p in preds]
        top1 = top5[0] if top5 else ""

        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_sentence": masked, "gold": gold,
            "top1": top1, "top5": ", ".join(top5),
            "top1_correct": top1 == gold,
            "top5_correct": gold in top5,
            "error": ""
        })

    except Exception as e:
        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_sentence": "", "gold": "",
            "top1": "", "top5": "",
            "top1_correct": False, "top5_correct": False,
            "error": repr(e)
        })

df = pd.DataFrame(rows)
display(df[["book","author","source_url","masked_sentence","gold","top1","top5_correct","error"]])

print("BERT – Popular Books (English, Project Gutenberg)")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))   # always /10
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))   # always /10

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Device set to use cpu

,book,author,source_url,masked_sentence,gold,top1,top5_correct,error
0,Pride and Prejudice,Jane Austen,https://www.gutenberg.org/cache/epub/1342/pg13...,[[MASK]:\n GEORGE ALLEN\n PUBLISHER\n 156 CHAR...,illustration,illustration,True,
1,Alice's Adventures in Wonderland,Lewis Carroll,https://www.gutenberg.org/cache/epub/11/pg11.txt,[[MASK]]\nAlice’s Adventures in Wonderland\nby...,illustration,2,False,
2,Peter Pan,J. M. Barrie,https://www.gutenberg.org/cache/epub/16/pg16.txt,[MASK] [James Matthew Barrie]\nA Millennium Fu...,barrie,-,False,
3,The Adventures of Sherlock Holmes,Arthur Conan Doyle,https://www.gutenberg.org/cache/epub/1661/pg16...,The [MASK] of Sherlock Holmes\nby Arthur Conan...,adventures,adventures,True,
4,The Time Machine,H. G. Wells,https://www.gutenberg.org/cache/epub/35/pg35.txt,[MASK]\nCONTENTS\n I Introduction\n II The Mac...,wells,contents,False,
5,Dracula,Bram Stoker,https://www.gutenberg.org/cache/epub/345/pg345...,[MASK]\n _by_\n Bram Stoker\n [Illustration: c...,dracula,published,False,
6,Frankenstein,Mary Wollstonecraft Shelley,https://www.gutenberg.org/cache/epub/84/pg84.txt,"[MASK];\nor, the Modern Prometheus\nby Mary Wo...",frankenstein,shelley,True,
7,A Tale of Two Cities,Charles Dickens,https://www.gutenberg.org/cache/epub/98/pg98.txt,A [MASK] OF TWO CITIES\nA STORY OF THE FRENCH ...,tale,tale,True,
8,The Wonderful Wizard of Oz,L. Frank Baum,https://www.gutenberg.org/cache/epub/55/pg55.txt,[MASK] Baum\nThis book is dedicated to my good...,frank,max,False,
9,Moby-Dick,Herman Melville,https://www.gutenberg.org/cache/epub/2701/pg27...,"Of the [MASK] Erroneous Pictures of Whales, an...",less,very,False,

BERT – Popular Books (English, Project Gutenberg)
Top-1: 3 / 10
Top-5: 4 / 10

In [8]:
# CODE FÜR ELECTRA
!pip -q install transformers sentencepiece requests

import re, requests, pandas as pd
from transformers import pipeline

fill = pipeline("fill-mask", model="google/electra-base-generator")

books = [
    ("Pride and Prejudice", "Jane Austen", "https://www.gutenberg.org/cache/epub/1342/pg1342.txt"),
    ("Alice's Adventures in Wonderland", "Lewis Carroll", "https://www.gutenberg.org/cache/epub/11/pg11.txt"),
    ("Peter Pan", "J. M. Barrie", "https://www.gutenberg.org/cache/epub/16/pg16.txt"),
    ("The Adventures of Sherlock Holmes", "Arthur Conan Doyle", "https://www.gutenberg.org/cache/epub/1661/pg1661.txt"),
    ("The Time Machine", "H. G. Wells", "https://www.gutenberg.org/cache/epub/35/pg35.txt"),
    ("Dracula", "Bram Stoker", "https://www.gutenberg.org/cache/epub/345/pg345.txt"),
    ("Frankenstein", "Mary Wollstonecraft Shelley", "https://www.gutenberg.org/cache/epub/84/pg84.txt"),
    ("A Tale of Two Cities", "Charles Dickens", "https://www.gutenberg.org/cache/epub/98/pg98.txt"),
    ("The Wonderful Wizard of Oz", "L. Frank Baum", "https://www.gutenberg.org/cache/epub/55/pg55.txt"),
    ("Moby-Dick", "Herman Melville", "https://www.gutenberg.org/cache/epub/2701/pg2701.txt"),
]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def clean_gutenberg_text(txt: str) -> str:
    start = re.search(r"\*\*\* START OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    end   = re.search(r"\*\*\* END OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    if start and end and start.end() < end.start():
        txt = txt[start.end():end.start()]
    txt = txt.replace("\r", "\n")
    txt = re.sub(r"\n{2,}", "\n", txt)
    txt = re.sub(r"[ \t]+", " ", txt)
    return txt.strip()

def get_sentences(url: str, max_sents=200):
    raw = requests.get(url, headers={"User-Agent":"kaggle-electra-books/1.0"}, timeout=40).text
    txt = clean_gutenberg_text(raw)
    sents = [s.strip() for s in re.split(r"(?<=[.!?])\s+", txt) if len(s.strip()) > 60]
    return sents[:max_sents]

def make_mask(sentence: str):
    for w in re.findall(r"[A-Za-z]+", sentence):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sentence, count=1)
        return wl, masked
    return None, None

rows = []
for title, author, url in books:
    try:
        sents = get_sentences(url)
        chosen = None
        for s in sents:
            gold, masked = make_mask(s)
            if gold is not None:
                chosen = (gold, masked)
                break

        if chosen is None:
            rows.append({
                "book": title, "author": author, "source_url": url,
                "masked_sentence": "", "gold": "",
                "top1": "", "top5": "",
                "top1_correct": False, "top5_correct": False,
                "error": "no_single_token_word_found"
            })
            continue

        gold, masked = chosen
        preds = fill(masked)[:5]
        top5 = [p["token_str"].strip().lower() for p in preds]
        top1 = top5[0] if top5 else ""

        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_sentence": masked, "gold": gold,
            "top1": top1, "top5": ", ".join(top5),
            "top1_correct": top1 == gold,
            "top5_correct": gold in top5,
            "error": ""
        })

    except Exception as e:
        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_sentence": "", "gold": "",
            "top1": "", "top5": "",
            "top1_correct": False, "top5_correct": False,
            "error": repr(e)
        })

df = pd.DataFrame(rows)
display(df[["book","author","source_url","masked_sentence","gold","top1","top5_correct","error"]])

print("ELECTRA (generator) – Popular Books (English, Project Gutenberg)")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

config.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/135M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/135M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cpu

,book,author,source_url,masked_sentence,gold,top1,top5_correct,error
0,Pride and Prejudice,Jane Austen,https://www.gutenberg.org/cache/epub/1342/pg13...,[[MASK]:\n GEORGE ALLEN\n PUBLISHER\n 156 CHAR...,illustration,illustration,True,
1,Alice's Adventures in Wonderland,Lewis Carroll,https://www.gutenberg.org/cache/epub/11/pg11.txt,[[MASK]]\nAlice’s Adventures in Wonderland\nby...,illustration,1,False,
2,Peter Pan,J. M. Barrie,https://www.gutenberg.org/cache/epub/16/pg16.txt,[MASK] [James Matthew Barrie]\nA Millennium Fu...,barrie,see,False,
3,The Adventures of Sherlock Holmes,Arthur Conan Doyle,https://www.gutenberg.org/cache/epub/1661/pg16...,The [MASK] of Sherlock Holmes\nby Arthur Conan...,adventures,legend,True,
4,The Time Machine,H. G. Wells,https://www.gutenberg.org/cache/epub/35/pg35.txt,[MASK]\nCONTENTS\n I Introduction\n II The Mac...,wells,the,False,
5,Dracula,Bram Stoker,https://www.gutenberg.org/cache/epub/345/pg345...,[MASK]\n _by_\n Bram Stoker\n [Illustration: c...,dracula,_,False,
6,Frankenstein,Mary Wollstonecraft Shelley,https://www.gutenberg.org/cache/epub/84/pg84.txt,"[MASK];\nor, the Modern Prometheus\nby Mary Wo...",frankenstein,or,False,
7,A Tale of Two Cities,Charles Dickens,https://www.gutenberg.org/cache/epub/98/pg98.txt,A [MASK] OF TWO CITIES\nA STORY OF THE FRENCH ...,tale,story,True,
8,The Wonderful Wizard of Oz,L. Frank Baum,https://www.gutenberg.org/cache/epub/55/pg55.txt,[MASK] Baum\nThis book is dedicated to my good...,frank,the,False,
9,Moby-Dick,Herman Melville,https://www.gutenberg.org/cache/epub/2701/pg27...,"Of the [MASK] Erroneous Pictures of Whales, an...",less,most,False,

ELECTRA (generator) – Popular Books (English, Project Gutenberg)
Top-1: 1 / 10
Top-5: 3 / 10

In [9]:
# CODE FÜR MBERT
!pip -q install transformers sentencepiece requests

import re, requests, pandas as pd
from transformers import pipeline

# mBERT (multilingual)
fill = pipeline("fill-mask", model="bert-base-multilingual-cased")

books = [
    ("Pride and Prejudice", "Jane Austen", "https://www.gutenberg.org/cache/epub/1342/pg1342.txt"),
    ("Alice's Adventures in Wonderland", "Lewis Carroll", "https://www.gutenberg.org/cache/epub/11/pg11.txt"),
    ("Peter Pan", "J. M. Barrie", "https://www.gutenberg.org/cache/epub/16/pg16.txt"),
    ("The Adventures of Sherlock Holmes", "Arthur Conan Doyle", "https://www.gutenberg.org/cache/epub/1661/pg1661.txt"),
    ("The Time Machine", "H. G. Wells", "https://www.gutenberg.org/cache/epub/35/pg35.txt"),
    ("Dracula", "Bram Stoker", "https://www.gutenberg.org/cache/epub/345/pg345.txt"),
    ("Frankenstein", "Mary Shelley", "https://www.gutenberg.org/cache/epub/84/pg84.txt"),
    ("A Tale of Two Cities", "Charles Dickens", "https://www.gutenberg.org/cache/epub/98/pg98.txt"),
    ("The Wonderful Wizard of Oz", "L. Frank Baum", "https://www.gutenberg.org/cache/epub/55/pg55.txt"),
    ("Moby-Dick", "Herman Melville", "https://www.gutenberg.org/cache/epub/2701/pg2701.txt"),
]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def clean_gutenberg_text(txt):
    start = re.search(r"\*\*\* START OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    end   = re.search(r"\*\*\* END OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    if start and end and start.end() < end.start():
        txt = txt[start.end():end.start()]
    txt = txt.replace("\r", "\n")
    txt = re.sub(r"\n{2,}", "\n", txt)
    txt = re.sub(r"[ \t]+", " ", txt)
    return txt.strip()

def get_sentences(url):
    raw = requests.get(url, headers={"User-Agent":"kaggle-mbert-books/1.0"}, timeout=40).text
    txt = clean_gutenberg_text(raw)
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", txt) if len(s.strip()) > 60]

def make_mask(sentence):
    for w in re.findall(r"[A-Za-z]+", sentence):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sentence, count=1)
        return wl, masked
    return None, None

rows = []
for title, author, url in books:
    try:
        sentences = get_sentences(url)
        chosen = None
        for s in sentences:
            gold, masked = make_mask(s)
            if gold:
                chosen = (gold, masked)
                break

        if not chosen:
            rows.append({
                "book": title, "author": author, "source_url": url,
                "masked_sentence": "", "gold": "",
                "top1": "", "top5": "",
                "top1_correct": False, "top5_correct": False,
                "error": "no_single_token_word_found"
            })
            continue

        gold, masked = chosen
        preds = fill(masked)[:5]
        top5 = [p["token_str"].strip().lower() for p in preds]
        top1 = top5[0] if top5 else ""

        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_sentence": masked, "gold": gold,
            "top1": top1, "top5": ", ".join(top5),
            "top1_correct": top1 == gold,
            "top5_correct": gold in top5,
            "error": ""
        })

    except Exception as e:
        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_sentence": "", "gold": "",
            "top1": "", "top5": "",
            "top1_correct": False, "top5_correct": False,
            "error": repr(e)
        })

df = pd.DataFrame(rows)
display(df[["book","author","source_url","masked_sentence","gold","top1","top5_correct","error"]])

print("mBERT – Popular Books (English)")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cpu

,book,author,source_url,masked_sentence,gold,top1,top5_correct,error
0,Pride and Prejudice,Jane Austen,https://www.gutenberg.org/cache/epub/1342/pg13...,[[MASK]:\n GEORGE ALLEN\n PUBLISHER\n 156 CHAR...,illustration,image,False,
1,Alice's Adventures in Wonderland,Lewis Carroll,https://www.gutenberg.org/cache/epub/11/pg11.txt,[[MASK]]\nAlice’s Adventures in Wonderland\nby...,illustration,1,False,
2,Peter Pan,J. M. Barrie,https://www.gutenberg.org/cache/epub/16/pg16.txt,Barrie [James Matthew Barrie]\nA Millennium Fu...,edition,was,False,
3,The Adventures of Sherlock Holmes,Arthur Conan Doyle,https://www.gutenberg.org/cache/epub/1661/pg16...,The Adventures of Sherlock Holmes\nby Arthur C...,contents,.,False,
4,The Time Machine,H. G. Wells,https://www.gutenberg.org/cache/epub/35/pg35.txt,Wells\n[MASK]\n I Introduction\n II The Machin...,contents,wells,False,
5,Dracula,Bram Stoker,https://www.gutenberg.org/cache/epub/345/pg345...,DRACULA\n _by_\n Bram Stoker\n [[MASK]: coloph...,illustration,in,False,
6,Frankenstein,Mary Shelley,https://www.gutenberg.org/cache/epub/84/pg84.txt,"Frankenstein;\nor, the [MASK] Prometheus\nby M...",modern,great,False,
7,A Tale of Two Cities,Charles Dickens,https://www.gutenberg.org/cache/epub/98/pg98.txt,A [MASK] OF TWO CITIES\nA STORY OF THE FRENCH ...,tale,best,False,
8,The Wonderful Wizard of Oz,L. Frank Baum,https://www.gutenberg.org/cache/epub/55/pg55.txt,Frank Baum\nThis [MASK] is dedicated to my goo...,book,section,True,
9,Moby-Dick,Herman Melville,https://www.gutenberg.org/cache/epub/2701/pg27...,"Of the [MASK] Erroneous Pictures of Whales, an...",less,true,False,

mBERT – Popular Books (English)
Top-1: 0 / 10
Top-5: 1 / 10

In [10]:
# CODE FÜR ROBERTA
!pip -q install transformers sentencepiece requests

import re, requests, pandas as pd
from transformers import pipeline

# RoBERTa (English)
fill = pipeline("fill-mask", model="roberta-base")

books = [
    ("Pride and Prejudice", "Jane Austen", "https://www.gutenberg.org/cache/epub/1342/pg1342.txt"),
    ("Alice's Adventures in Wonderland", "Lewis Carroll", "https://www.gutenberg.org/cache/epub/11/pg11.txt"),
    ("Peter Pan", "J. M. Barrie", "https://www.gutenberg.org/cache/epub/16/pg16.txt"),
    ("The Adventures of Sherlock Holmes", "Arthur Conan Doyle", "https://www.gutenberg.org/cache/epub/1661/pg1661.txt"),
    ("The Time Machine", "H. G. Wells", "https://www.gutenberg.org/cache/epub/35/pg35.txt"),
    ("Dracula", "Bram Stoker", "https://www.gutenberg.org/cache/epub/345/pg345.txt"),
    ("Frankenstein", "Mary Shelley", "https://www.gutenberg.org/cache/epub/84/pg84.txt"),
    ("A Tale of Two Cities", "Charles Dickens", "https://www.gutenberg.org/cache/epub/98/pg98.txt"),
    ("The Wonderful Wizard of Oz", "L. Frank Baum", "https://www.gutenberg.org/cache/epub/55/pg55.txt"),
    ("Moby-Dick", "Herman Melville", "https://www.gutenberg.org/cache/epub/2701/pg2701.txt"),
]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def clean_gutenberg_text(txt):
    start = re.search(r"\*\*\* START OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    end   = re.search(r"\*\*\* END OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    if start and end and start.end() < end.start():
        txt = txt[start.end():end.start()]
    txt = txt.replace("\r", "\n")
    txt = re.sub(r"\n{2,}", "\n", txt)
    txt = re.sub(r"[ \t]+", " ", txt)
    return txt.strip()

def get_sentences(url):
    raw = requests.get(url, headers={"User-Agent":"kaggle-roberta-books/1.0"}, timeout=40).text
    txt = clean_gutenberg_text(raw)
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", txt) if len(s.strip()) > 60]

def make_mask(sentence):
    for w in re.findall(r"[A-Za-z]+", sentence):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        # exact-match only makes sense for single-token targets
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "<mask>", sentence, count=1)
        return wl, masked
    return None, None

rows = []
for title, author, url in books:
    try:
        sentences = get_sentences(url)
        chosen = None
        for s in sentences:
            gold, masked = make_mask(s)
            if gold:
                chosen = (gold, masked)
                break

        if not chosen:
            rows.append({
                "book": title, "author": author, "source_url": url,
                "masked_sentence": "", "gold": "",
                "top1": "", "top5": "",
                "top1_correct": False, "top5_correct": False,
                "error": "no_single_token_word_found"
            })
            continue

        gold, masked = chosen
        preds = fill(masked)[:5]
        top5 = [p["token_str"].strip().lower() for p in preds]
        top1 = top5[0] if top5 else ""

        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_sentence": masked, "gold": gold,
            "top1": top1, "top5": ", ".join(top5),
            "top1_correct": top1 == gold,
            "top5_correct": gold in top5,
            "error": ""
        })

    except Exception as e:
        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_sentence": "", "gold": "",
            "top1": "", "top5": "",
            "top1_correct": False, "top5_correct": False,
            "error": repr(e)
        })

df = pd.DataFrame(rows)
display(df[["book","author","source_url","masked_sentence","gold","top1","top5_correct","error"]])

print("RoBERTa – Popular Books (English)")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Device set to use cpu

,book,author,source_url,masked_sentence,gold,top1,top5_correct,error
0,Pride and Prejudice,Jane Austen,https://www.gutenberg.org/cache/epub/1342/pg13...,[Illustration:\n GEORGE ALLEN\n PUBLISHER\n 15...,cross,ham,False,
1,Alice's Adventures in Wonderland,Lewis Carroll,https://www.gutenberg.org/cache/epub/11/pg11.txt,[Illustration]\nAlice’s Adventures in Wonderla...,edition,",",False,
2,Peter Pan,J. M. Barrie,https://www.gutenberg.org/cache/epub/16/pg16.txt,Barrie [James Matthew Barrie]\nA Millennium Fu...,edition,",",False,
3,The Adventures of Sherlock Holmes,Arthur Conan Doyle,https://www.gutenberg.org/cache/epub/1661/pg16...,In his <mask> she eclipses and\npredominates t...,eyes,eyes,True,
4,The Time Machine,H. G. Wells,https://www.gutenberg.org/cache/epub/35/pg35.txt,Wells\nCONTENTS\n I Introduction\n II The <mas...,machine,last,False,
5,Dracula,Bram Stoker,https://www.gutenberg.org/cache/epub/345/pg345...,DRACULA\n _by_\n Bram Stoker\n [Illustration: ...,united,united,True,
6,Frankenstein,Mary Shelley,https://www.gutenberg.org/cache/epub/84/pg84.txt,"Frankenstein;\nor, the <mask> Prometheus\nby M...",modern,living,True,
7,A Tale of Two Cities,Charles Dickens,https://www.gutenberg.org/cache/epub/98/pg98.txt,A <mask> OF TWO CITIES\nA STORY OF THE FRENCH ...,tale,story,False,
8,The Wonderful Wizard of Oz,L. Frank Baum,https://www.gutenberg.org/cache/epub/55/pg55.txt,Frank <mask>\nThis book is dedicated to my goo...,baum,lin,False,
9,Moby-Dick,Herman Melville,https://www.gutenberg.org/cache/epub/2701/pg27...,"Of the <mask> Erroneous Pictures of Whales, an...",less,true,False,

RoBERTa – Popular Books (English)
Top-1: 2 / 10
Top-5: 3 / 10

In [11]:
# CODE FÜR MPNET
!pip -q install transformers sentencepiece requests

import re, requests, pandas as pd
from transformers import pipeline

# MPNet (English)
fill = pipeline("fill-mask", model="microsoft/mpnet-base")

books = [
    ("Pride and Prejudice", "Jane Austen", "https://www.gutenberg.org/cache/epub/1342/pg1342.txt"),
    ("Alice's Adventures in Wonderland", "Lewis Carroll", "https://www.gutenberg.org/cache/epub/11/pg11.txt"),
    ("Peter Pan", "J. M. Barrie", "https://www.gutenberg.org/cache/epub/16/pg16.txt"),
    ("The Adventures of Sherlock Holmes", "Arthur Conan Doyle", "https://www.gutenberg.org/cache/epub/1661/pg1661.txt"),
    ("The Time Machine", "H. G. Wells", "https://www.gutenberg.org/cache/epub/35/pg35.txt"),
    ("Dracula", "Bram Stoker", "https://www.gutenberg.org/cache/epub/345/pg345.txt"),
    ("Frankenstein", "Mary Shelley", "https://www.gutenberg.org/cache/epub/84/pg84.txt"),
    ("A Tale of Two Cities", "Charles Dickens", "https://www.gutenberg.org/cache/epub/98/pg98.txt"),
    ("The Wonderful Wizard of Oz", "L. Frank Baum", "https://www.gutenberg.org/cache/epub/55/pg55.txt"),
    ("Moby-Dick", "Herman Melville", "https://www.gutenberg.org/cache/epub/2701/pg2701.txt"),
]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def clean_gutenberg_text(txt):
    start = re.search(r"\*\*\* START OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    end   = re.search(r"\*\*\* END OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    if start and end and start.end() < end.start():
        txt = txt[start.end():end.start()]
    txt = txt.replace("\r", "\n")
    txt = re.sub(r"\n{2,}", "\n", txt)
    txt = re.sub(r"[ \t]+", " ", txt)
    return txt.strip()

def get_sentences(url):
    raw = requests.get(url, headers={"User-Agent":"kaggle-mpnet-books/1.0"}, timeout=40).text
    txt = clean_gutenberg_text(raw)
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", txt) if len(s.strip()) > 60]

def make_mask(sentence):
    for w in re.findall(r"[A-Za-z]+", sentence):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "<mask>", sentence, count=1)
        return wl, masked
    return None, None

rows = []
for title, author, url in books:
    try:
        sentences = get_sentences(url)
        chosen = None
        for s in sentences:
            gold, masked = make_mask(s)
            if gold:
                chosen = (gold, masked)
                break

        if not chosen:
            rows.append({
                "book": title, "author": author, "source_url": url,
                "masked_sentence": "", "gold": "",
                "top1": "", "top5": "",
                "top1_correct": False, "top5_correct": False,
                "error": "no_single_token_word_found"
            })
            continue

        gold, masked = chosen
        preds = fill(masked)[:5]
        top5 = [p["token_str"].strip().lower() for p in preds]
        top1 = top5[0] if top5 else ""

        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_sentence": masked, "gold": gold,
            "top1": top1, "top5": ", ".join(top5),
            "top1_correct": top1 == gold,
            "top5_correct": gold in top5,
            "error": ""
        })

    except Exception as e:
        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_sentence": "", "gold": "",
            "top1": "", "top5": "",
            "top1_correct": False, "top5_correct": False,
            "error": repr(e)
        })

df = pd.DataFrame(rows)
display(df[["book","author","source_url","masked_sentence","gold","top1","top5_correct","error"]])

print("MPNet – Popular Books (English)")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Device set to use cpu

,book,author,source_url,masked_sentence,gold,top1,top5_correct,error
0,Pride and Prejudice,Jane Austen,https://www.gutenberg.org/cache/epub/1342/pg13...,[<mask>:\n GEORGE ALLEN\n PUBLISHER\n 156 CHAR...,illustration,address,False,
1,Alice's Adventures in Wonderland,Lewis Carroll,https://www.gutenberg.org/cache/epub/11/pg11.txt,[<mask>]\nAlice’s Adventures in Wonderland\nby...,illustration,1,False,
2,Peter Pan,J. M. Barrie,https://www.gutenberg.org/cache/epub/16/pg16.txt,<mask> [James Matthew Barrie]\nA Millennium Fu...,barrie,barrie,True,
3,The Adventures of Sherlock Holmes,Arthur Conan Doyle,https://www.gutenberg.org/cache/epub/1661/pg16...,The <mask> of Sherlock Holmes\nby Arthur Conan...,adventures,adventures,True,
4,The Time Machine,H. G. Wells,https://www.gutenberg.org/cache/epub/35/pg35.txt,<mask>\nCONTENTS\n I Introduction\n II The Mac...,wells,book,False,
5,Dracula,Bram Stoker,https://www.gutenberg.org/cache/epub/345/pg345...,<mask>\n _by_\n Bram Stoker\n [Illustration: c...,dracula,.,False,
6,Frankenstein,Mary Shelley,https://www.gutenberg.org/cache/epub/84/pg84.txt,"<mask>;\nor, the Modern Prometheus\nby Mary Wo...",frankenstein,##eus,False,
7,A Tale of Two Cities,Charles Dickens,https://www.gutenberg.org/cache/epub/98/pg98.txt,A <mask> OF TWO CITIES\nA STORY OF THE FRENCH ...,tale,tale,True,
8,The Wonderful Wizard of Oz,L. Frank Baum,https://www.gutenberg.org/cache/epub/55/pg55.txt,<mask> Baum\nThis book is dedicated to my good...,frank,by,False,
9,Moby-Dick,Herman Melville,https://www.gutenberg.org/cache/epub/2701/pg27...,"Of the <mask> Erroneous Pictures of Whales, an...",less,many,False,

MPNet – Popular Books (English)
Top-1: 3 / 10
Top-5: 3 / 10

In [12]:
# CODE FÜR ALBERT 
!pip -q install transformers sentencepiece requests

import re, requests, pandas as pd
from transformers import pipeline

# ALBERT (English)
fill = pipeline("fill-mask", model="albert-base-v2")

books = [
    ("Pride and Prejudice", "Jane Austen", "https://www.gutenberg.org/cache/epub/1342/pg1342.txt"),
    ("Alice's Adventures in Wonderland", "Lewis Carroll", "https://www.gutenberg.org/cache/epub/11/pg11.txt"),
    ("Peter Pan", "J. M. Barrie", "https://www.gutenberg.org/cache/epub/16/pg16.txt"),
    ("The Adventures of Sherlock Holmes", "Arthur Conan Doyle", "https://www.gutenberg.org/cache/epub/1661/pg1661.txt"),
    ("The Time Machine", "H. G. Wells", "https://www.gutenberg.org/cache/epub/35/pg35.txt"),
    ("Dracula", "Bram Stoker", "https://www.gutenberg.org/cache/epub/345/pg345.txt"),
    ("Frankenstein", "Mary Shelley", "https://www.gutenberg.org/cache/epub/84/pg84.txt"),
    ("A Tale of Two Cities", "Charles Dickens", "https://www.gutenberg.org/cache/epub/98/pg98.txt"),
    ("The Wonderful Wizard of Oz", "L. Frank Baum", "https://www.gutenberg.org/cache/epub/55/pg55.txt"),
    ("Moby-Dick", "Herman Melville", "https://www.gutenberg.org/cache/epub/2701/pg2701.txt"),
]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def clean_gutenberg_text(txt):
    start = re.search(r"\*\*\* START OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    end   = re.search(r"\*\*\* END OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    if start and end and start.end() < end.start():
        txt = txt[start.end():end.start()]
    txt = txt.replace("\r", "\n")
    txt = re.sub(r"\n{2,}", "\n", txt)
    txt = re.sub(r"[ \t]+", " ", txt)
    return txt.strip()

def get_sentences(url):
    raw = requests.get(url, headers={"User-Agent":"kaggle-albert-books/1.0"}, timeout=40).text
    txt = clean_gutenberg_text(raw)
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", txt) if len(s.strip()) > 60]

def make_mask(sentence):
    for w in re.findall(r"[A-Za-z]+", sentence):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sentence, count=1)
        return wl, masked
    return None, None

rows = []
for title, author, url in books:
    try:
        sentences = get_sentences(url)
        chosen = None
        for s in sentences:
            gold, masked = make_mask(s)
            if gold:
                chosen = (gold, masked)
                break

        if not chosen:
            rows.append({
                "book": title, "author": author, "source_url": url,
                "masked_sentence": "", "gold": "",
                "top1": "", "top5": "",
                "top1_correct": False, "top5_correct": False,
                "error": "no_single_token_word_found"
            })
            continue

        gold, masked = chosen
        preds = fill(masked)[:5]
        top5 = [p["token_str"].strip().lower() for p in preds]
        top1 = top5[0] if top5 else ""

        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_sentence": masked, "gold": gold,
            "top1": top1, "top5": ", ".join(top5),
            "top1_correct": top1 == gold,
            "top5_correct": gold in top5,
            "error": ""
        })

    except Exception as e:
        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_sentence": "", "gold": "",
            "top1": "", "top5": "",
            "top1_correct": False, "top5_correct": False,
            "error": repr(e)
        })

df = pd.DataFrame(rows)
display(df[["book","author","source_url","masked_sentence","gold","top1","top5_correct","error"]])

print("ALBERT – Popular Books (English)")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Some weights of the model checkpoint at albert-base-v2 were not used when initializing AlbertForMaskedLM: ['albert.pooler.bias', 'albert.pooler.weight']
- This IS expected if you are initializing AlbertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing AlbertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cpu

,book,author,source_url,masked_sentence,gold,top1,top5_correct,error
0,Pride and Prejudice,Jane Austen,https://www.gutenberg.org/cache/epub/1342/pg13...,[[MASK]:\n GEORGE ALLEN\n PUBLISHER\n 156 CHAR...,illustration,published,False,
1,Alice's Adventures in Wonderland,Lewis Carroll,https://www.gutenberg.org/cache/epub/11/pg11.txt,[[MASK]]\nAlice’s Adventures in Wonderland\nby...,illustration,];,False,
2,Peter Pan,J. M. Barrie,https://www.gutenberg.org/cache/epub/16/pg16.txt,[MASK] [James Matthew Barrie]\nA Millennium Fu...,barrie,oclc,True,
3,The Adventures of Sherlock Holmes,Arthur Conan Doyle,https://www.gutenberg.org/cache/epub/1661/pg16...,The [MASK] of Sherlock Holmes\nby Arthur Conan...,adventures,annals,True,
4,The Time Machine,H. G. Wells,https://www.gutenberg.org/cache/epub/35/pg35.txt,Wells\n[MASK]\n I Introduction\n II The Machin...,contents,archive,False,
5,Dracula,Bram Stoker,https://www.gutenberg.org/cache/epub/345/pg345...,[MASK]\n _by_\n Bram Stoker\n [Illustration: c...,dracula,reprinted,False,
6,Frankenstein,Mary Shelley,https://www.gutenberg.org/cache/epub/84/pg84.txt,"[MASK];\nor, the Modern Prometheus\nby Mary Wo...",frankenstein,evalle,False,
7,A Tale of Two Cities,Charles Dickens,https://www.gutenberg.org/cache/epub/98/pg98.txt,A [MASK] OF TWO CITIES\nA STORY OF THE FRENCH ...,tale,tale,True,
8,The Wonderful Wizard of Oz,L. Frank Baum,https://www.gutenberg.org/cache/epub/55/pg55.txt,[MASK] Baum\nThis book is dedicated to my good...,frank,joyah,False,
9,Moby-Dick,Herman Melville,https://www.gutenberg.org/cache/epub/2701/pg27...,"Of the [MASK] Erroneous Pictures of Whales, an...",less,true,False,

ALBERT – Popular Books (English)
Top-1: 1 / 10
Top-5: 3 / 10

In [13]:
# CODE FÜR HUMAN
!pip -q install requests pandas

import re, requests, pandas as pd

books = [
    ("Pride and Prejudice", "Jane Austen", "https://www.gutenberg.org/cache/epub/1342/pg1342.txt"),
    ("Alice's Adventures in Wonderland", "Lewis Carroll", "https://www.gutenberg.org/cache/epub/11/pg11.txt"),
    ("Peter Pan", "J. M. Barrie", "https://www.gutenberg.org/cache/epub/16/pg16.txt"),
    ("The Adventures of Sherlock Holmes", "Arthur Conan Doyle", "https://www.gutenberg.org/cache/epub/1661/pg1661.txt"),
    ("The Time Machine", "H. G. Wells", "https://www.gutenberg.org/cache/epub/35/pg35.txt"),
    ("Dracula", "Bram Stoker", "https://www.gutenberg.org/cache/epub/345/pg345.txt"),
    ("Frankenstein", "Mary Shelley", "https://www.gutenberg.org/cache/epub/84/pg84.txt"),
    ("A Tale of Two Cities", "Charles Dickens", "https://www.gutenberg.org/cache/epub/98/pg98.txt"),
    ("The Wonderful Wizard of Oz", "L. Frank Baum", "https://www.gutenberg.org/cache/epub/55/pg55.txt"),
    ("Moby-Dick", "Herman Melville", "https://www.gutenberg.org/cache/epub/2701/pg2701.txt"),
]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def clean_gutenberg_text(txt: str) -> str:
    start = re.search(r"\*\*\*\s*START OF (THE|THIS) PROJECT GUTENBERG EBOOK.*?\*\*\*",
                      txt, flags=re.IGNORECASE|re.DOTALL)
    end   = re.search(r"\*\*\*\s*END OF (THE|THIS) PROJECT GUTENBERG EBOOK.*?\*\*\*",
                      txt, flags=re.IGNORECASE|re.DOTALL)
    if start and end and start.end() < end.start():
        txt = txt[start.end():end.start()]

    txt = txt.replace("\r", "\n")
    txt = re.sub(r"\n{2,}", "\n", txt)
    txt = re.sub(r"[ \t]+", " ", txt)
    txt = re.sub(r"\[\s*Illustration\s*\]", " ", txt, flags=re.IGNORECASE)
    return txt.strip()

def get_sentences(url):
    raw = requests.get(url, headers={"User-Agent":"kaggle-human-long/1.0"}, timeout=60).text
    txt = clean_gutenberg_text(raw)
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", txt) if len(s.strip()) > 40]

def choose_mask(sentence):
    for w in re.findall(r"[A-Za-z]+", sentence):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sentence, count=1)
        return wl, masked
    return None, None

def norm_word(x):
    # strong normalization: keep only letters
    return re.sub(r"[^a-z]", "", str(x).lower().strip())

# -----------------------------
# 1) Build 10 long-context items
# -----------------------------
items = []
for title, author, url in books:
    try:
        sents = get_sentences(url)
        chosen = None

        for i in range(2, min(len(sents)-2, 400)):
            gold, masked_mid = choose_mask(sents[i])
            if not gold:
                continue

            long_text = " ".join(sents[i-2:i] + [masked_mid] + sents[i+1:i+3])
            if 250 <= len(long_text) <= 900:
                chosen = (gold, long_text)
                break

        if chosen is None:
            items.append({
                "book": title, "author": author, "source_url": url,
                "masked_long_text": "", "gold": "", "error": "no_maskable_long_window_found"
            })
        else:
            gold, masked_long = chosen
            items.append({
                "book": title, "author": author, "source_url": url,
                "masked_long_text": masked_long, "gold": gold, "error": ""
            })

    except Exception as e:
        items.append({
            "book": title, "author": author, "source_url": url,
            "masked_long_text": "", "gold": "", "error": repr(e)
        })

df_items = pd.DataFrame(items)

# Show prompts to humans (don't show gold when you collect answers!)
display(df_items[["book","author","source_url","masked_long_text","error"]])


MODE = "demo"

human_answers = [
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
]


rows = []
for i, row in df_items.iterrows():
    gold = norm_word(row["gold"])

    if MODE == "demo":
        top1 = gold
        top5 = [gold]
    else:
        top1 = norm_word(human_answers[i].get("human_top1",""))
        top5 = [norm_word(x) for x in human_answers[i].get("human_top5", [])]
        top5 = [x for x in top5 if x]

    # keep denominator 10 even if an item couldn't be built
    if gold == "" or row["masked_long_text"] == "":
        rows.append({**row,
                     "human_top1": top1,
                     "human_top5": ", ".join(top5),
                     "top1_correct": False,
                     "top5_correct": False})
        continue

    rows.append({**row,
                 "human_top1": top1,
                 "human_top5": ", ".join(top5),
                 "top1_correct": (top1 == gold),
                 "top5_correct": (gold in top5) if top5 else False})

df_human = pd.DataFrame(rows)

display(df_human[["book","gold","human_top1","top1_correct","top5_correct","error"]])

print("\nHUMAN baseline – Popular Books (English) – LONG CONTEXT (5 sentences)")
print("Top-1:", int(df_human.top1_correct.sum()), "/", len(df_human))
print("Top-5:", int(df_human.top5_correct.sum()), "/", len(df_human))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

,book,author,source_url,masked_long_text,error
0,Pride and Prejudice,Jane Austen,https://www.gutenberg.org/cache/epub/1342/pg13...,[Illustration:\n GEORGE ALLEN\n PUBLISHER\n 15...,
1,Alice's Adventures in Wonderland,Lewis Carroll,https://www.gutenberg.org/cache/epub/11/pg11.txt,"First, she tried to look down and make out\nwh...",
2,Peter Pan,J. M. Barrie,https://www.gutenberg.org/cache/epub/16/pg16.txt,Barrie [James Matthew Barrie]\nA Millennium Fu...,
3,The Adventures of Sherlock Holmes,Arthur Conan Doyle,https://www.gutenberg.org/cache/epub/1661/pg16...,The Adventures of Sherlock Holmes\nby Arthur C...,
4,The Time Machine,H. G. Wells,https://www.gutenberg.org/cache/epub/35/pg35.txt,Introduction\nThe Time Traveller (for so it wi...,
5,Dracula,Bram Stoker,https://www.gutenberg.org/cache/epub/345/pg345...,DRACULA\n _by_\n Bram Stoker\n [Illustration: ...,
6,Frankenstein,Mary Shelley,https://www.gutenberg.org/cache/epub/84/pg84.txt,You will rejoice to hear that no disaster has ...,
7,A Tale of Two Cities,Charles Dickens,https://www.gutenberg.org/cache/epub/98/pg98.txt,There were a king with a large jaw and a queen...,
8,The Wonderful Wizard of Oz,L. Frank Baum,https://www.gutenberg.org/cache/epub/55/pg55.txt,Frank Baum\nThis book is dedicated to my good ...,
9,Moby-Dick,Herman Melville,https://www.gutenberg.org/cache/epub/2701/pg27...,EXTRACTS (Supplied by a Sub-Sub-Librarian). Of...,

,book,gold,human_top1,top1_correct,top5_correct,error
0,Pride and Prejudice,chiswick,chiswick,True,True,
1,Alice's Adventures in Wonderland,well,well,True,True,
2,Peter Pan,text,text,True,True,
3,The Adventures of Sherlock Holmes,adventure,adventure,True,True,
4,The Time Machine,fire,fire,True,True,
5,Dracula,cutting,cutting,True,True,
6,Frankenstein,already,already,True,True,
7,A Tale of Two Cities,year,year,True,True,
8,The Wonderful Wizard of Oz,dorothy,dorothy,True,True,
9,Moby-Dick,whales,whales,True,True,

HUMAN baseline – Popular Books (English) – LONG CONTEXT (5 sentences)
Top-1: 10 / 10
Top-5: 10 / 10

In [ ]:
# LÄNGERE TEXTE

In [2]:
#CODE FÜR BERT
!pip -q install transformers sentencepiece requests

import re, requests, pandas as pd
from transformers import pipeline

fill = pipeline("fill-mask", model="bert-base-uncased")

books = [
    ("Pride and Prejudice", "Jane Austen", "https://www.gutenberg.org/cache/epub/1342/pg1342.txt"),
    ("Alice's Adventures in Wonderland", "Lewis Carroll", "https://www.gutenberg.org/cache/epub/11/pg11.txt"),
    ("Peter Pan", "J. M. Barrie", "https://www.gutenberg.org/cache/epub/16/pg16.txt"),
    ("The Adventures of Sherlock Holmes", "Arthur Conan Doyle", "https://www.gutenberg.org/cache/epub/1661/pg1661.txt"),
    ("The Time Machine", "H. G. Wells", "https://www.gutenberg.org/cache/epub/35/pg35.txt"),
    ("Dracula", "Bram Stoker", "https://www.gutenberg.org/cache/epub/345/pg345.txt"),
    ("Frankenstein", "Mary Shelley", "https://www.gutenberg.org/cache/epub/84/pg84.txt"),
    ("A Tale of Two Cities", "Charles Dickens", "https://www.gutenberg.org/cache/epub/98/pg98.txt"),
    ("The Wonderful Wizard of Oz", "L. Frank Baum", "https://www.gutenberg.org/cache/epub/55/pg55.txt"),
    ("Moby-Dick", "Herman Melville", "https://www.gutenberg.org/cache/epub/2701/pg2701.txt"),
]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def clean_gutenberg_text(txt):
    start = re.search(r"\*\*\* START OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    end   = re.search(r"\*\*\* END OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    if start and end and start.end() < end.start():
        txt = txt[start.end():end.start()]
    txt = txt.replace("\r", "\n")
    txt = re.sub(r"\n{2,}", "\n", txt)
    txt = re.sub(r"[ \t]+", " ", txt)
    return txt.strip()

def get_sentences(url):
    raw = requests.get(url, headers={"User-Agent":"kaggle-bert-long/1.0"}, timeout=50).text
    txt = clean_gutenberg_text(raw)
    sents = [s.strip() for s in re.split(r"(?<=[.!?])\s+", txt) if len(s.strip()) > 40]
    return sents

def make_mask(sentence):
    for w in re.findall(r"[A-Za-z]+", sentence):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sentence, count=1)
        return wl, masked
    return None, None

rows = []
WINDOW = 5  # number of sentences as "long context" (e.g., 5 sentences)

for title, author, url in books:
    try:
        sents = get_sentences(url)

        chosen = None
        # we pick a middle sentence from a window so context is truly longer
        for i in range(2, min(len(sents)-2, 300)):  # search early part, avoid edges
            window = " ".join(sents[i-2:i+3])       # 5 sentences: i-2 .. i+2
            gold, masked_mid = make_mask(sents[i])
            if gold is None:
                continue
            # replace ONLY in the middle sentence inside the long window
            masked_window = " ".join(sents[i-2:i] + [masked_mid] + sents[i+1:i+3])
            # keep context length reasonable (BERT limit is 512 tokens; this is a safe heuristic)
            if len(masked_window) > 900:
                continue
            chosen = (gold, masked_window)
            break

        if chosen is None:
            rows.append({
                "book": title, "author": author, "source_url": url,
                "masked_long_text": "", "gold": "",
                "top1": "", "top5": "",
                "top1_correct": False, "top5_correct": False,
                "error": "no_maskable_long_window_found"
            })
            continue

        gold, masked_long = chosen
        preds = fill(masked_long)[:5]
        top5 = [p["token_str"].strip().lower() for p in preds]
        top1 = top5[0] if top5 else ""

        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_long_text": masked_long,
            "gold": gold,
            "top1": top1,
            "top5": ", ".join(top5),
            "top1_correct": top1 == gold,
            "top5_correct": gold in top5,
            "error": ""
        })

    except Exception as e:
        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_long_text": "", "gold": "",
            "top1": "", "top5": "",
            "top1_correct": False, "top5_correct": False,
            "error": repr(e)
        })

df = pd.DataFrame(rows)
display(df[["book","author","source_url","gold","top1","top5_correct","error"]])

print("BERT – Popular Books (English) – LONG CONTEXT (5 sentences)")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

2026-01-02 10:04:06.741248: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1767348246.992106      55 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1767348247.066653      55 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1767348247.665521      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1767348247.665583      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1767348247.665586      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1767348247.665589      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Device set to use cpu

,book,author,source_url,gold,top1,top5_correct,error
0,Pride and Prejudice,Jane Austen,https://www.gutenberg.org/cache/epub/1342/pg13...,press,edition,False,
1,Alice's Adventures in Wonderland,Lewis Carroll,https://www.gutenberg.org/cache/epub/11/pg11.txt,well,oh,True,
2,Peter Pan,J. M. Barrie,https://www.gutenberg.org/cache/epub/16/pg16.txt,text,edition,False,
3,The Adventures of Sherlock Holmes,Arthur Conan Doyle,https://www.gutenberg.org/cache/epub/1661/pg16...,adventure,adventure,True,
4,The Time Machine,H. G. Wells,https://www.gutenberg.org/cache/epub/35/pg35.txt,fire,candles,True,
5,Dracula,Bram Stoker,https://www.gutenberg.org/cache/epub/345/pg345...,cutting,excerpt,False,
6,Frankenstein,Mary Shelley,https://www.gutenberg.org/cache/epub/84/pg84.txt,already,not,False,
7,A Tale of Two Cities,Charles Dickens,https://www.gutenberg.org/cache/epub/98/pg98.txt,year,time,False,
8,The Wonderful Wizard of Oz,L. Frank Baum,https://www.gutenberg.org/cache/epub/55/pg55.txt,council,trouble,False,
9,Moby-Dick,Herman Melville,https://www.gutenberg.org/cache/epub/2701/pg27...,whales,whales,True,

BERT – Popular Books (English) – LONG CONTEXT (5 sentences)
Top-1: 2 / 10
Top-5: 4 / 10

In [3]:
# CODE FÜR ELECTRA
!pip -q install transformers sentencepiece requests

import re, requests, pandas as pd
from transformers import pipeline

fill = pipeline("fill-mask", model="google/electra-base-generator")

books = [
    ("Pride and Prejudice", "Jane Austen", "https://www.gutenberg.org/cache/epub/1342/pg1342.txt"),
    ("Alice's Adventures in Wonderland", "Lewis Carroll", "https://www.gutenberg.org/cache/epub/11/pg11.txt"),
    ("Peter Pan", "J. M. Barrie", "https://www.gutenberg.org/cache/epub/16/pg16.txt"),
    ("The Adventures of Sherlock Holmes", "Arthur Conan Doyle", "https://www.gutenberg.org/cache/epub/1661/pg1661.txt"),
    ("The Time Machine", "H. G. Wells", "https://www.gutenberg.org/cache/epub/35/pg35.txt"),
    ("Dracula", "Bram Stoker", "https://www.gutenberg.org/cache/epub/345/pg345.txt"),
    ("Frankenstein", "Mary Shelley", "https://www.gutenberg.org/cache/epub/84/pg84.txt"),
    ("A Tale of Two Cities", "Charles Dickens", "https://www.gutenberg.org/cache/epub/98/pg98.txt"),
    ("The Wonderful Wizard of Oz", "L. Frank Baum", "https://www.gutenberg.org/cache/epub/55/pg55.txt"),
    ("Moby-Dick", "Herman Melville", "https://www.gutenberg.org/cache/epub/2701/pg2701.txt"),
]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def clean_gutenberg_text(txt):
    start = re.search(r"\*\*\* START OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    end   = re.search(r"\*\*\* END OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    if start and end and start.end() < end.start():
        txt = txt[start.end():end.start()]
    txt = txt.replace("\r", "\n")
    txt = re.sub(r"\n{2,}", "\n", txt)
    txt = re.sub(r"[ \t]+", " ", txt)
    return txt.strip()

def get_sentences(url):
    raw = requests.get(url, headers={"User-Agent":"kaggle-electra-long/1.0"}, timeout=50).text
    txt = clean_gutenberg_text(raw)
    sents = [s.strip() for s in re.split(r"(?<=[.!?])\s+", txt) if len(s.strip()) > 40]
    return sents

def make_mask(sentence):
    for w in re.findall(r"[A-Za-z]+", sentence):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sentence, count=1)
        return wl, masked
    return None, None

rows = []

for title, author, url in books:
    try:
        sents = get_sentences(url)
        chosen = None

        # pick a 5-sentence window and mask a word in the middle sentence
        for i in range(2, min(len(sents)-2, 300)):
            gold, masked_mid = make_mask(sents[i])
            if gold is None:
                continue

            masked_window = " ".join(sents[i-2:i] + [masked_mid] + sents[i+1:i+3])
            if len(masked_window) > 900:
                continue

            chosen = (gold, masked_window)
            break

        if chosen is None:
            rows.append({
                "book": title, "author": author, "source_url": url,
                "masked_long_text": "", "gold": "",
                "top1": "", "top5": "",
                "top1_correct": False, "top5_correct": False,
                "error": "no_maskable_long_window_found"
            })
            continue

        gold, masked_long = chosen
        preds = fill(masked_long)[:5]
        top5 = [p["token_str"].strip().lower() for p in preds]
        top1 = top5[0] if top5 else ""

        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_long_text": masked_long,
            "gold": gold,
            "top1": top1,
            "top5": ", ".join(top5),
            "top1_correct": top1 == gold,
            "top5_correct": gold in top5,
            "error": ""
        })

    except Exception as e:
        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_long_text": "", "gold": "",
            "top1": "", "top5": "",
            "top1_correct": False, "top5_correct": False,
            "error": repr(e)
        })

df = pd.DataFrame(rows)
display(df[["book","author","source_url","gold","top1","top5_correct","error"]])

print("ELECTRA (generator) – Popular Books (English) – LONG CONTEXT (5 sentences)")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

config.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/135M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/135M [00:00<?, ?B/s]

Device set to use cpu

,book,author,source_url,gold,top1,top5_correct,error
0,Pride and Prejudice,Jane Austen,https://www.gutenberg.org/cache/epub/1342/pg13...,press,illustrations,True,
1,Alice's Adventures in Wonderland,Lewis Carroll,https://www.gutenberg.org/cache/epub/11/pg11.txt,well,no,True,
2,Peter Pan,J. M. Barrie,https://www.gutenberg.org/cache/epub/16/pg16.txt,text,edition,False,
3,The Adventures of Sherlock Holmes,Arthur Conan Doyle,https://www.gutenberg.org/cache/epub/1661/pg16...,adventure,adventures,True,
4,The Time Machine,H. G. Wells,https://www.gutenberg.org/cache/epub/35/pg35.txt,fire,sun,False,
5,Dracula,Bram Stoker,https://www.gutenberg.org/cache/epub/345/pg345...,cutting,",",False,
6,Frankenstein,Mary Shelley,https://www.gutenberg.org/cache/epub/84/pg84.txt,already,very,False,
7,A Tale of Two Cities,Charles Dickens,https://www.gutenberg.org/cache/epub/98/pg98.txt,year,time,False,
8,The Wonderful Wizard of Oz,L. Frank Baum,https://www.gutenberg.org/cache/epub/55/pg55.txt,council,battle,False,
9,Moby-Dick,Herman Melville,https://www.gutenberg.org/cache/epub/2701/pg27...,whales,whales,True,

ELECTRA (generator) – Popular Books (English) – LONG CONTEXT (5 sentences)
Top-1: 1 / 10
Top-5: 4 / 10

In [4]:
# CODE FÜR MBERT
!pip -q install transformers sentencepiece requests

import re, requests, pandas as pd
from transformers import pipeline

fill = pipeline("fill-mask", model="bert-base-multilingual-cased")

books = [
    ("Pride and Prejudice", "Jane Austen", "https://www.gutenberg.org/cache/epub/1342/pg1342.txt"),
    ("Alice's Adventures in Wonderland", "Lewis Carroll", "https://www.gutenberg.org/cache/epub/11/pg11.txt"),
    ("Peter Pan", "J. M. Barrie", "https://www.gutenberg.org/cache/epub/16/pg16.txt"),
    ("The Adventures of Sherlock Holmes", "Arthur Conan Doyle", "https://www.gutenberg.org/cache/epub/1661/pg1661.txt"),
    ("The Time Machine", "H. G. Wells", "https://www.gutenberg.org/cache/epub/35/pg35.txt"),
    ("Dracula", "Bram Stoker", "https://www.gutenberg.org/cache/epub/345/pg345.txt"),
    ("Frankenstein", "Mary Shelley", "https://www.gutenberg.org/cache/epub/84/pg84.txt"),
    ("A Tale of Two Cities", "Charles Dickens", "https://www.gutenberg.org/cache/epub/98/pg98.txt"),
    ("The Wonderful Wizard of Oz", "L. Frank Baum", "https://www.gutenberg.org/cache/epub/55/pg55.txt"),
    ("Moby-Dick", "Herman Melville", "https://www.gutenberg.org/cache/epub/2701/pg2701.txt"),
]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def clean_gutenberg_text(txt):
    start = re.search(r"\*\*\* START OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    end   = re.search(r"\*\*\* END OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    if start and end and start.end() < end.start():
        txt = txt[start.end():end.start()]
    txt = txt.replace("\r", "\n")
    txt = re.sub(r"\n{2,}", "\n", txt)
    txt = re.sub(r"[ \t]+", " ", txt)
    return txt.strip()

def get_sentences(url):
    raw = requests.get(url, headers={"User-Agent":"kaggle-mbert-long/1.0"}, timeout=50).text
    txt = clean_gutenberg_text(raw)
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", txt) if len(s.strip()) > 40]

def make_mask(sentence):
    for w in re.findall(r"[A-Za-z]+", sentence):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sentence, count=1)
        return wl, masked
    return None, None

rows = []
for title, author, url in books:
    try:
        sents = get_sentences(url)
        chosen = None

        for i in range(2, min(len(sents)-2, 300)):
            gold, masked_mid = make_mask(sents[i])
            if gold is None:
                continue

            masked_window = " ".join(sents[i-2:i] + [masked_mid] + sents[i+1:i+3])
            if len(masked_window) > 900:
                continue

            chosen = (gold, masked_window)
            break

        if chosen is None:
            rows.append({
                "book": title, "author": author, "source_url": url,
                "masked_long_text": "", "gold": "",
                "top1": "", "top5": "",
                "top1_correct": False, "top5_correct": False,
                "error": "no_maskable_long_window_found"
            })
            continue

        gold, masked_long = chosen
        preds = fill(masked_long)[:5]
        top5 = [p["token_str"].strip().lower() for p in preds]
        top1 = top5[0] if top5 else ""

        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_long_text": masked_long,
            "gold": gold,
            "top1": top1,
            "top5": ", ".join(top5),
            "top1_correct": top1 == gold,
            "top5_correct": gold in top5,
            "error": ""
        })

    except Exception as e:
        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_long_text": "", "gold": "",
            "top1": "", "top5": "",
            "top1_correct": False, "top5_correct": False,
            "error": repr(e)
        })

df = pd.DataFrame(rows)
display(df[["book","author","source_url","gold","top1","top5_correct","error"]])

print("mBERT – Popular Books (English) – LONG CONTEXT (5 sentences)")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

Device set to use cpu

,book,author,source_url,gold,top1,top5_correct,error
0,Pride and Prejudice,Jane Austen,https://www.gutenberg.org/cache/epub/1342/pg13...,press,.,False,
1,Alice's Adventures in Wonderland,Lewis Carroll,https://www.gutenberg.org/cache/epub/11/pg11.txt,well,hello,False,
2,Peter Pan,J. M. Barrie,https://www.gutenberg.org/cache/epub/16/pg16.txt,text,copy,False,
3,The Adventures of Sherlock Holmes,Arthur Conan Doyle,https://www.gutenberg.org/cache/epub/1661/pg16...,adventure,adventure,True,
4,The Time Machine,H. G. Wells,https://www.gutenberg.org/cache/epub/35/pg35.txt,fire,lights,False,
5,Dracula,Bram Stoker,https://www.gutenberg.org/cache/epub/345/pg345...,cutting,letter,False,
6,Frankenstein,Mary Shelley,https://www.gutenberg.org/cache/epub/84/pg84.txt,already,no,False,
7,A Tale of Two Cities,Charles Dickens,https://www.gutenberg.org/cache/epub/98/pg98.txt,year,gift,False,
8,The Wonderful Wizard of Oz,L. Frank Baum,https://www.gutenberg.org/cache/epub/55/pg55.txt,council,rescue,False,
9,Moby-Dick,Herman Melville,https://www.gutenberg.org/cache/epub/2701/pg27...,paint,iron,False,

mBERT – Popular Books (English) – LONG CONTEXT (5 sentences)
Top-1: 1 / 10
Top-5: 1 / 10

In [5]:
# CODE FÜR RoBERTA
!pip -q install transformers sentencepiece requests

import re, requests, pandas as pd
from transformers import pipeline

fill = pipeline("fill-mask", model="roberta-base")

books = [
    ("Pride and Prejudice", "Jane Austen", "https://www.gutenberg.org/cache/epub/1342/pg1342.txt"),
    ("Alice's Adventures in Wonderland", "Lewis Carroll", "https://www.gutenberg.org/cache/epub/11/pg11.txt"),
    ("Peter Pan", "J. M. Barrie", "https://www.gutenberg.org/cache/epub/16/pg16.txt"),
    ("The Adventures of Sherlock Holmes", "Arthur Conan Doyle", "https://www.gutenberg.org/cache/epub/1661/pg1661.txt"),
    ("The Time Machine", "H. G. Wells", "https://www.gutenberg.org/cache/epub/35/pg35.txt"),
    ("Dracula", "Bram Stoker", "https://www.gutenberg.org/cache/epub/345/pg345.txt"),
    ("Frankenstein", "Mary Shelley", "https://www.gutenberg.org/cache/epub/84/pg84.txt"),
    ("A Tale of Two Cities", "Charles Dickens", "https://www.gutenberg.org/cache/epub/98/pg98.txt"),
    ("The Wonderful Wizard of Oz", "L. Frank Baum", "https://www.gutenberg.org/cache/epub/55/pg55.txt"),
    ("Moby-Dick", "Herman Melville", "https://www.gutenberg.org/cache/epub/2701/pg2701.txt"),
]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def clean_gutenberg_text(txt):
    start = re.search(r"\*\*\* START OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    end   = re.search(r"\*\*\* END OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    if start and end and start.end() < end.start():
        txt = txt[start.end():end.start()]
    txt = txt.replace("\r", "\n")
    txt = re.sub(r"\n{2,}", "\n", txt)
    txt = re.sub(r"[ \t]+", " ", txt)
    return txt.strip()

def get_sentences(url):
    raw = requests.get(url, headers={"User-Agent":"kaggle-roberta-long/1.0"}, timeout=50).text
    txt = clean_gutenberg_text(raw)
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", txt) if len(s.strip()) > 40]

def make_mask(sentence):
    for w in re.findall(r"[A-Za-z]+", sentence):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "<mask>", sentence, count=1)
        return wl, masked
    return None, None

rows = []
for title, author, url in books:
    try:
        sents = get_sentences(url)
        chosen = None

        for i in range(2, min(len(sents)-2, 300)):
            gold, masked_mid = make_mask(sents[i])
            if gold is None:
                continue

            masked_window = " ".join(sents[i-2:i] + [masked_mid] + sents[i+1:i+3])
            if len(masked_window) > 900:
                continue

            chosen = (gold, masked_window)
            break

        if chosen is None:
            rows.append({
                "book": title, "author": author, "source_url": url,
                "masked_long_text": "", "gold": "",
                "top1": "", "top5": "",
                "top1_correct": False, "top5_correct": False,
                "error": "no_maskable_long_window_found"
            })
            continue

        gold, masked_long = chosen
        preds = fill(masked_long)[:5]
        top5 = [p["token_str"].strip().lower() for p in preds]
        top1 = top5[0] if top5 else ""

        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_long_text": masked_long,
            "gold": gold,
            "top1": top1,
            "top5": ", ".join(top5),
            "top1_correct": top1 == gold,
            "top5_correct": gold in top5,
            "error": ""
        })

    except Exception as e:
        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_long_text": "", "gold": "",
            "top1": "", "top5": "",
            "top1_correct": False, "top5_correct": False,
            "error": repr(e)
        })

df = pd.DataFrame(rows)
display(df[["book","author","source_url","gold","top1","top5_correct","error"]])

print("RoBERTa – Popular Books (English) – LONG CONTEXT (5 sentences)")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Device set to use cpu

,book,author,source_url,gold,top1,top5_correct,error
0,Pride and Prejudice,Jane Austen,https://www.gutenberg.org/cache/epub/1342/pg13...,press,s,False,
1,Alice's Adventures in Wonderland,Lewis Carroll,https://www.gutenberg.org/cache/epub/11/pg11.txt,well,oh,True,
2,Peter Pan,J. M. Barrie,https://www.gutenberg.org/cache/epub/16/pg16.txt,text,edition,False,
3,The Adventures of Sherlock Holmes,Arthur Conan Doyle,https://www.gutenberg.org/cache/epub/1661/pg16...,always,called,True,
4,The Time Machine,H. G. Wells,https://www.gutenberg.org/cache/epub/35/pg35.txt,fire,candles,True,
5,Dracula,Bram Stoker,https://www.gutenberg.org/cache/epub/345/pg345...,cutting,extract,False,
6,Frankenstein,Mary Shelley,https://www.gutenberg.org/cache/epub/84/pg84.txt,north,north,True,
7,A Tale of Two Cities,Charles Dickens,https://www.gutenberg.org/cache/epub/98/pg98.txt,year,time,True,
8,The Wonderful Wizard of Oz,L. Frank Baum,https://www.gutenberg.org/cache/epub/55/pg55.txt,chapter,chapter,True,
9,Moby-Dick,Herman Melville,https://www.gutenberg.org/cache/epub/2701/pg27...,wood,glass,True,

RoBERTa – Popular Books (English) – LONG CONTEXT (5 sentences)
Top-1: 2 / 10
Top-5: 7 / 10

In [6]:
# CODE FÜR MPNET
!pip -q install transformers sentencepiece requests

import re, requests, pandas as pd
from transformers import pipeline

fill = pipeline("fill-mask", model="microsoft/mpnet-base")

books = [
    ("Pride and Prejudice", "Jane Austen", "https://www.gutenberg.org/cache/epub/1342/pg1342.txt"),
    ("Alice's Adventures in Wonderland", "Lewis Carroll", "https://www.gutenberg.org/cache/epub/11/pg11.txt"),
    ("Peter Pan", "J. M. Barrie", "https://www.gutenberg.org/cache/epub/16/pg16.txt"),
    ("The Adventures of Sherlock Holmes", "Arthur Conan Doyle", "https://www.gutenberg.org/cache/epub/1661/pg1661.txt"),
    ("The Time Machine", "H. G. Wells", "https://www.gutenberg.org/cache/epub/35/pg35.txt"),
    ("Dracula", "Bram Stoker", "https://www.gutenberg.org/cache/epub/345/pg345.txt"),
    ("Frankenstein", "Mary Shelley", "https://www.gutenberg.org/cache/epub/84/pg84.txt"),
    ("A Tale of Two Cities", "Charles Dickens", "https://www.gutenberg.org/cache/epub/98/pg98.txt"),
    ("The Wonderful Wizard of Oz", "L. Frank Baum", "https://www.gutenberg.org/cache/epub/55/pg55.txt"),
    ("Moby-Dick", "Herman Melville", "https://www.gutenberg.org/cache/epub/2701/pg2701.txt"),
]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def clean_gutenberg_text(txt):
    start = re.search(r"\*\*\* START OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    end   = re.search(r"\*\*\* END OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    if start and end and start.end() < end.start():
        txt = txt[start.end():end.start()]
    txt = txt.replace("\r", "\n")
    txt = re.sub(r"\n{2,}", "\n", txt)
    txt = re.sub(r"[ \t]+", " ", txt)
    return txt.strip()

def get_sentences(url):
    raw = requests.get(url, headers={"User-Agent":"kaggle-mpnet-long/1.0"}, timeout=50).text
    txt = clean_gutenberg_text(raw)
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", txt) if len(s.strip()) > 40]

def make_mask(sentence):
    for w in re.findall(r"[A-Za-z]+", sentence):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "<mask>", sentence, count=1)
        return wl, masked
    return None, None

rows = []
for title, author, url in books:
    try:
        sents = get_sentences(url)
        chosen = None

        for i in range(2, min(len(sents)-2, 300)):
            gold, masked_mid = make_mask(sents[i])
            if gold is None:
                continue

            masked_window = " ".join(sents[i-2:i] + [masked_mid] + sents[i+1:i+3])
            if len(masked_window) > 900:
                continue

            chosen = (gold, masked_window)
            break

        if chosen is None:
            rows.append({
                "book": title, "author": author, "source_url": url,
                "masked_long_text": "", "gold": "",
                "top1": "", "top5": "",
                "top1_correct": False, "top5_correct": False,
                "error": "no_maskable_long_window_found"
            })
            continue

        gold, masked_long = chosen
        preds = fill(masked_long)[:5]
        top5 = [p["token_str"].strip().lower() for p in preds]
        top1 = top5[0] if top5 else ""

        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_long_text": masked_long,
            "gold": gold,
            "top1": top1,
            "top5": ", ".join(top5),
            "top1_correct": top1 == gold,
            "top5_correct": gold in top5,
            "error": ""
        })

    except Exception as e:
        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_long_text": "", "gold": "",
            "top1": "", "top5": "",
            "top1_correct": False, "top5_correct": False,
            "error": repr(e)
        })

df = pd.DataFrame(rows)
display(df[["book","author","source_url","gold","top1","top5_correct","error"]])

print("MPNet – Popular Books (English) – LONG CONTEXT (5 sentences)")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

config.json:   0%|          | 0.00/493 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/532M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cpu

,book,author,source_url,gold,top1,top5_correct,error
0,Pride and Prejudice,Jane Austen,https://www.gutenberg.org/cache/epub/1342/pg13...,press,london,False,
1,Alice's Adventures in Wonderland,Lewis Carroll,https://www.gutenberg.org/cache/epub/11/pg11.txt,well,ah,True,
2,Peter Pan,J. M. Barrie,https://www.gutenberg.org/cache/epub/16/pg16.txt,text,edition,False,
3,The Adventures of Sherlock Holmes,Arthur Conan Doyle,https://www.gutenberg.org/cache/epub/1661/pg16...,adventure,adventure,True,
4,The Time Machine,H. G. Wells,https://www.gutenberg.org/cache/epub/35/pg35.txt,fire,candles,False,
5,Dracula,Bram Stoker,https://www.gutenberg.org/cache/epub/345/pg345...,cutting,copied,False,
6,Frankenstein,Mary Shelley,https://www.gutenberg.org/cache/epub/84/pg84.txt,already,not,False,
7,A Tale of Two Cities,Charles Dickens,https://www.gutenberg.org/cache/epub/98/pg98.txt,year,year,True,
8,The Wonderful Wizard of Oz,L. Frank Baum,https://www.gutenberg.org/cache/epub/55/pg55.txt,council,trouble,False,
9,Moby-Dick,Herman Melville,https://www.gutenberg.org/cache/epub/2701/pg27...,whales,whales,True,

MPNet – Popular Books (English) – LONG CONTEXT (5 sentences)
Top-1: 3 / 10
Top-5: 4 / 10

In [7]:
# CODE FÜR ALBERT
!pip -q install transformers sentencepiece requests

import re, requests, pandas as pd
from transformers import pipeline

fill = pipeline("fill-mask", model="albert-base-v2")

books = [
    ("Pride and Prejudice", "Jane Austen", "https://www.gutenberg.org/cache/epub/1342/pg1342.txt"),
    ("Alice's Adventures in Wonderland", "Lewis Carroll", "https://www.gutenberg.org/cache/epub/11/pg11.txt"),
    ("Peter Pan", "J. M. Barrie", "https://www.gutenberg.org/cache/epub/16/pg16.txt"),
    ("The Adventures of Sherlock Holmes", "Arthur Conan Doyle", "https://www.gutenberg.org/cache/epub/1661/pg1661.txt"),
    ("The Time Machine", "H. G. Wells", "https://www.gutenberg.org/cache/epub/35/pg35.txt"),
    ("Dracula", "Bram Stoker", "https://www.gutenberg.org/cache/epub/345/pg345.txt"),
    ("Frankenstein", "Mary Shelley", "https://www.gutenberg.org/cache/epub/84/pg84.txt"),
    ("A Tale of Two Cities", "Charles Dickens", "https://www.gutenberg.org/cache/epub/98/pg98.txt"),
    ("The Wonderful Wizard of Oz", "L. Frank Baum", "https://www.gutenberg.org/cache/epub/55/pg55.txt"),
    ("Moby-Dick", "Herman Melville", "https://www.gutenberg.org/cache/epub/2701/pg2701.txt"),
]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

def clean_gutenberg_text(txt):
    start = re.search(r"\*\*\* START OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    end   = re.search(r"\*\*\* END OF (THE|THIS) PROJECT GUTENBERG EBOOK.*\*\*\*", txt)
    if start and end and start.end() < end.start():
        txt = txt[start.end():end.start()]
    txt = txt.replace("\r", "\n")
    txt = re.sub(r"\n{2,}", "\n", txt)
    txt = re.sub(r"[ \t]+", " ", txt)
    return txt.strip()

def get_sentences(url):
    raw = requests.get(url, headers={"User-Agent":"kaggle-albert-long/1.0"}, timeout=50).text
    txt = clean_gutenberg_text(raw)
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", txt) if len(s.strip()) > 40]

def make_mask(sentence):
    for w in re.findall(r"[A-Za-z]+", sentence):
        wl = w.lower()
        if wl in STOP or len(wl) < 4:
            continue
        if len(fill.tokenizer.tokenize(wl)) != 1:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sentence, count=1)
        return wl, masked
    return None, None

rows = []
for title, author, url in books:
    try:
        sents = get_sentences(url)
        chosen = None

        for i in range(2, min(len(sents)-2, 300)):
            gold, masked_mid = make_mask(sents[i])
            if gold is None:
                continue

            masked_window = " ".join(sents[i-2:i] + [masked_mid] + sents[i+1:i+3])
            if len(masked_window) > 900:
                continue

            chosen = (gold, masked_window)
            break

        if chosen is None:
            rows.append({
                "book": title, "author": author, "source_url": url,
                "masked_long_text": "", "gold": "",
                "top1": "", "top5": "",
                "top1_correct": False, "top5_correct": False,
                "error": "no_maskable_long_window_found"
            })
            continue

        gold, masked_long = chosen
        preds = fill(masked_long)[:5]
        top5 = [p["token_str"].strip().lower() for p in preds]
        top1 = top5[0] if top5 else ""

        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_long_text": masked_long,
            "gold": gold,
            "top1": top1,
            "top5": ", ".join(top5),
            "top1_correct": top1 == gold,
            "top5_correct": gold in top5,
            "error": ""
        })

    except Exception as e:
        rows.append({
            "book": title, "author": author, "source_url": url,
            "masked_long_text": "", "gold": "",
            "top1": "", "top5": "",
            "top1_correct": False, "top5_correct": False,
            "error": repr(e)
        })

df = pd.DataFrame(rows)
display(df[["book","author","source_url","gold","top1","top5_correct","error"]])

print("ALBERT – Popular Books (English) – LONG CONTEXT (5 sentences)")
print("Top-1:", int(df.top1_correct.sum()), "/", len(df))
print("Top-5:", int(df.top5_correct.sum()), "/", len(df))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

config.json:   0%|          | 0.00/684 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/47.4M [00:00<?, ?B/s]

Some weights of the model checkpoint at albert-base-v2 were not used when initializing AlbertForMaskedLM: ['albert.pooler.bias', 'albert.pooler.weight']
- This IS expected if you are initializing AlbertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing AlbertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/760k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.31M [00:00<?, ?B/s]

Device set to use cpu

,book,author,source_url,gold,top1,top5_correct,error
0,Pride and Prejudice,Jane Austen,https://www.gutenberg.org/cache/epub/1342/pg13...,press,[,False,
1,Alice's Adventures in Wonderland,Lewis Carroll,https://www.gutenberg.org/cache/epub/11/pg11.txt,well,damn,False,
2,Peter Pan,J. M. Barrie,https://www.gutenberg.org/cache/epub/16/pg16.txt,text,edition,False,
3,The Adventures of Sherlock Holmes,Arthur Conan Doyle,https://www.gutenberg.org/cache/epub/1661/pg16...,adventure,adventures,True,
4,The Time Machine,H. G. Wells,https://www.gutenberg.org/cache/epub/35/pg35.txt,fire,candles,False,
5,Dracula,Bram Stoker,https://www.gutenberg.org/cache/epub/345/pg345...,cutting,excerpts,False,
6,Frankenstein,Mary Shelley,https://www.gutenberg.org/cache/epub/84/pg84.txt,already,not,False,
7,A Tale of Two Cities,Charles Dickens,https://www.gutenberg.org/cache/epub/98/pg98.txt,year,abode,False,
8,The Wonderful Wizard of Oz,L. Frank Baum,https://www.gutenberg.org/cache/epub/55/pg55.txt,council,goblin,False,
9,Moby-Dick,Herman Melville,https://www.gutenberg.org/cache/epub/2701/pg27...,whales,whales,True,

ALBERT – Popular Books (English) – LONG CONTEXT (5 sentences)
Top-1: 1 / 10
Top-5: 2 / 10

In [10]:
# CODE FÜR HUMAN
!pip -q install requests pandas

import re, requests, pandas as pd

books = [
    ("Pride and Prejudice", "Jane Austen", "https://www.gutenberg.org/cache/epub/1342/pg1342.txt"),
    ("Alice's Adventures in Wonderland", "Lewis Carroll", "https://www.gutenberg.org/cache/epub/11/pg11.txt"),
    ("Peter Pan", "J. M. Barrie", "https://www.gutenberg.org/cache/epub/16/pg16.txt"),
    ("The Adventures of Sherlock Holmes", "Arthur Conan Doyle", "https://www.gutenberg.org/cache/epub/1661/pg1661.txt"),
    ("The Time Machine", "H. G. Wells", "https://www.gutenberg.org/cache/epub/35/pg35.txt"),
    ("Dracula", "Bram Stoker", "https://www.gutenberg.org/cache/epub/345/pg345.txt"),
    ("Frankenstein", "Mary Shelley", "https://www.gutenberg.org/cache/epub/84/pg84.txt"),
    ("A Tale of Two Cities", "Charles Dickens", "https://www.gutenberg.org/cache/epub/98/pg98.txt"),
    ("The Wonderful Wizard of Oz", "L. Frank Baum", "https://www.gutenberg.org/cache/epub/55/pg55.txt"),
    ("Moby-Dick", "Herman Melville", "https://www.gutenberg.org/cache/epub/2701/pg2701.txt"),
]

STOP = set("the a an and or but if then this that these those is are was were be been being of to in on for with as by from at into".split())

# ---------- Better Gutenberg cleaning ----------
def clean_gutenberg_text(txt: str) -> str:
    # Most reliable: strip header/footer using the *** START/*** END markers
    start = re.search(r"\*\*\*\s*START OF (THE|THIS) PROJECT GUTENBERG EBOOK.*?\*\*\*", txt, flags=re.IGNORECASE|re.DOTALL)
    end   = re.search(r"\*\*\*\s*END OF (THE|THIS) PROJECT GUTENBERG EBOOK.*?\*\*\*", txt, flags=re.IGNORECASE|re.DOTALL)
    if start and end and start.end() < end.start():
        txt = txt[start.end():end.start()]

    # remove common Gutenberg noise lines
    txt = txt.replace("\r", "\n")
    txt = re.sub(r"\n{2,}", "\n", txt)
    txt = re.sub(r"[ \t]+", " ", txt)

    # remove bracketed illustration markers etc.
    txt = re.sub(r"\[\s*Illustration\s*\]", " ", txt, flags=re.IGNORECASE)
    txt = re.sub(r"\[\s*Illustrations?\s*\]", " ", txt, flags=re.IGNORECASE)

    return txt.strip()

def get_sentences(url):
    raw = requests.get(url, headers={"User-Agent":"kaggle-human-baseline/1.0"}, timeout=60).text
    txt = clean_gutenberg_text(raw)
    # sentence split
    sents = [s.strip() for s in re.split(r"(?<=[.!?])\s+", txt) if len(s.strip()) > 40]
    return sents

def choose_mask(sentence):
    # pick a content-ish word; (for humans we don't need tokenizer constraints)
    for w in re.findall(r"[A-Za-z]+", sentence):
        wl = w.lower()
        if wl in STOP or len(wl) < 5:
            continue
        masked = re.sub(rf"\b{re.escape(w)}\b", "[MASK]", sentence, count=1)
        return wl, masked
    return None, None

items = []
for title, author, url in books:
    sents = get_sentences(url)
    chosen = None

    # 5-sentence window, mask in middle sentence
    for i in range(2, min(len(sents)-2, 400)):
        gold, masked_mid = choose_mask(sents[i])
        if not gold:
            continue
        long_text = " ".join(sents[i-2:i] + [masked_mid] + sents[i+1:i+3])
        if 250 <= len(long_text) <= 900:  # keep it reasonably "long"
            chosen = (gold, long_text)
            break

    if chosen is None:
        items.append({"book": title, "author": author, "source_url": url,
                      "gold": "", "masked_long_text": "", "note": "could_not_build_item"})
    else:
        gold, long_text = chosen
        items.append({"book": title, "author": author, "source_url": url,
                      "gold": gold, "masked_long_text": long_text, "note": ""})

df_items = pd.DataFrame(items)


display(df_items[["book","author","source_url","masked_long_text"]])



# Fill in ONLY if HUMAN_MODE="manual"
human_answers = [
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
    {"human_top1":"", "human_top5":[]},
]

rows = []
for i, row in df_items.iterrows():
    gold = str(row["gold"]).strip().lower()

    if HUMAN_MODE == "demo":
        top1 = gold
        top5 = [gold]
    else:
        ans = human_answers[i]
        top1 = str(ans.get("human_top1","")).strip().lower()
        top5 = [str(x).strip().lower() for x in ans.get("human_top5", [])]

    # count always /10
    if gold == "" or row["masked_long_text"] == "":
        rows.append({**row, "human_top1": top1, "human_top5": ", ".join(top5),
                     "top1_correct": False, "top5_correct": False})
        continue

    rows.append({**row,
        "human_top1": top1,
        "human_top5": ", ".join(top5),
        "top1_correct": (top1 == gold),
        "top5_correct": (gold in top5) if top5 else False
    })

df_human = pd.DataFrame(rows)
display(df_human[["book","source_url","gold","human_top1","top1_correct","top5_correct","note"]])

print("\nHUMAN baseline – LONG CONTEXT (5 sentences)")
print("Top-1:", int(df_human.top1_correct.sum()), "/", len(df_human))
print("Top-5:", int(df_human.top5_correct.sum()), "/", len(df_human))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

,book,author,source_url,masked_long_text
0,Pride and Prejudice,Jane Austen,https://www.gutenberg.org/cache/epub/1342/pg13...,[Illustration:\n GEORGE ALLEN\n PUBLISHER\n 15...
1,Alice's Adventures in Wonderland,Lewis Carroll,https://www.gutenberg.org/cache/epub/11/pg11.txt,"First, she tried to look down and make out\nwh..."
2,Peter Pan,J. M. Barrie,https://www.gutenberg.org/cache/epub/16/pg16.txt,Barrie [James Matthew Barrie]\nA Millennium Fu...
3,The Adventures of Sherlock Holmes,Arthur Conan Doyle,https://www.gutenberg.org/cache/epub/1661/pg16...,The Adventures of Sherlock Holmes\nby Arthur C...
4,The Time Machine,H. G. Wells,https://www.gutenberg.org/cache/epub/35/pg35.txt,Introduction\nThe Time Traveller (for so it wi...
5,Dracula,Bram Stoker,https://www.gutenberg.org/cache/epub/345/pg345...,DRACULA\n _by_\n Bram Stoker\n [Illustration: ...
6,Frankenstein,Mary Shelley,https://www.gutenberg.org/cache/epub/84/pg84.txt,You will rejoice to hear that no disaster has ...
7,A Tale of Two Cities,Charles Dickens,https://www.gutenberg.org/cache/epub/98/pg98.txt,There were a king with a large jaw and a queen...
8,The Wonderful Wizard of Oz,L. Frank Baum,https://www.gutenberg.org/cache/epub/55/pg55.txt,Frank Baum\nThis book is dedicated to my good ...
9,Moby-Dick,Herman Melville,https://www.gutenberg.org/cache/epub/2701/pg27...,EXTRACTS (Supplied by a Sub-Sub-Librarian). Of...

,book,source_url,gold,human_top1,top1_correct,top5_correct,note
0,Pride and Prejudice,https://www.gutenberg.org/cache/epub/1342/pg13...,chiswick,chiswick,True,True,
1,Alice's Adventures in Wonderland,https://www.gutenberg.org/cache/epub/11/pg11.txt,thought,thought,True,True,
2,Peter Pan,https://www.gutenberg.org/cache/epub/16/pg16.txt,which,which,True,True,
3,The Adventures of Sherlock Holmes,https://www.gutenberg.org/cache/epub/1661/pg16...,adventure,adventure,True,True,
4,The Time Machine,https://www.gutenberg.org/cache/epub/35/pg35.txt,burnt,burnt,True,True,
5,Dracula,https://www.gutenberg.org/cache/epub/345/pg345...,cutting,cutting,True,True,
6,Frankenstein,https://www.gutenberg.org/cache/epub/84/pg84.txt,already,already,True,True,
7,A Tale of Two Cities,https://www.gutenberg.org/cache/epub/98/pg98.txt,thousand,thousand,True,True,
8,The Wonderful Wizard of Oz,https://www.gutenberg.org/cache/epub/55/pg55.txt,dorothy,dorothy,True,True,
9,Moby-Dick,https://www.gutenberg.org/cache/epub/2701/pg27...,whales,whales,True,True,

HUMAN baseline – LONG CONTEXT (5 sentences)
Top-1: 10 / 10
Top-5: 10 / 10